#ifndef _ASD_ACC_UNIT_TEST_AUTOMATIC_H_
#define _ASD_ACC_UNIT_TEST_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    ACC_Unit_Test_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 14:49:57 Uhr
*
* @brief   "ACC_Unit_Test>>Automatic (project code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "assertLib_Assert_Impl.h"
#include "components_AccFeedbackTest_Automatic.h"
#include "components_AccFeedbackTest_disableFeedbackTest_Automatic.h"
#include "components_AccFeedbackTest_enableFeedbackTest_Automatic.h"
#include "components_Globals_Automatic.h"


/* component structure for project ACC_UNIT_TEST_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ....................ACC_Unit_Test_Automatic */
#define _ACC_Unit_Test_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by project ACC_Unit_Test_Automatic
 ******************************************************************************/



#endif /* _ASD_ACC_UNIT_TEST_AUTOMATIC_H_ */
