#ifndef _ASD_COMPONENTS_FUSITEST_AUTOMATIC_H_
#define _ASD_COMPONENTS_FUSITEST_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_FuSiTest_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 15:05:58 Uhr
*
* @brief   "components_FuSiTest>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "chartab.h"
#include "components_FuSi_Automatic.h"


/* component structure for module COMPONENTS_FUSITEST_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ..............components_FuSiTest_Automatic */
#define _components_FuSiTest_Automatic_TYPE_DEF_





#endif /* _ASD_COMPONENTS_FUSITEST_AUTOMATIC_H_ */
