/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_OnOffTest_testOnFailure_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 15:05:58 Uhr
*
* @brief   "components_OnOffTest_testOnFailure>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_OnOffTest_testOnFailure_Automatic.h"
#include "ACC_Unit_Test_Automatic.h"
#include "assertLib_Assert_Impl.h"
#include "components_Globals_Automatic.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_OnOffTest_testOnFailure'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_OnOffTest_testOnFailure_Automatic_testOnFailure'
 * ----------------------------------------------------------------------------
 * model name:...................................'testOnFailure'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_OnOffTest_testOnFailure_Automatic_testOnFailure (void)
{
   components_Globals_acc_status = false;
   ASSERT_FALSE(components_OnOff_Automatic_onoff(0.0F, true));
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_OnOffTest_testOnFailure_Automatic_testOnFailure'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



