#ifndef _ASD_COMPONENTS_HILLSVALLEYSTEST_AUTOMATIC_H_
#define _ASD_COMPONENTS_HILLSVALLEYSTEST_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_HillsValleysTest_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 15:05:58 Uhr
*
* @brief   "components_HillsValleysTest>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "chartab.h"
#include "components_Stecke_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_HillsValleysTest_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct components_HillsValleysTest_Automatic_CAL_MEM_SUBSTRUCT {
   struct components_Stecke_Automatic_CAL_MEM_SUBSTRUCT _stecke;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_HillsValleysTest_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_HillsValleysTest_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_HillsValleysTest_Automatic_RAM_SUBSTRUCT {
   struct components_Stecke_Automatic_RAM_SUBSTRUCT _stecke;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_HillsValleysTest_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR MODULE 'components_HillsValleysTest_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct components_HillsValleysTest_Automatic {
   struct components_Stecke_Automatic _stecke;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR MODULE 'components_HillsValleysTest_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ......components_HillsValleysTest_Automatic */
#define _components_HillsValleysTest_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'components_HillsValleysTest_CAL_MEM' */
/* containing 'CAL_MEM' memory class tree */
extern const volatile struct components_HillsValleysTest_Automatic_CAL_MEM_SUBSTRUCT components_HillsValleysTest_CAL_MEM;

/* forward declaration of substruct variable 'components_HillsValleysTest_RAM' */
/* containing 'RAM' memory class tree */
extern struct components_HillsValleysTest_Automatic_RAM_SUBSTRUCT components_HillsValleysTest_RAM;

/* forward declaration of component variable 'components_HillsValleysTest' */
/* containing 'ROM' memory class tree */
extern const struct components_HillsValleysTest_Automatic components_HillsValleysTest;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module components_HillsValleysTest_Automatic
 ******************************************************************************/
extern void components_HillsValleysTest_Automatic_SlopeTest (void);



#endif /* _ASD_COMPONENTS_HILLSVALLEYSTEST_AUTOMATIC_H_ */
