#ifndef _ASD_COMPONENTS_ONOFFTEST_TESTON_AUTOMATIC_H_
#define _ASD_COMPONENTS_ONOFFTEST_TESTON_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_OnOffTest_testOn_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 15:05:58 Uhr
*
* @brief   "components_OnOffTest_testOn>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "chartab.h"
#include "components_OnOff_Automatic.h"


/* component structure for module COMPONENTS_ONOFFTEST_TESTON_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ......components_OnOffTest_testOn_Automatic */
#define _components_OnOffTest_testOn_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by module components_OnOffTest_testOn_Automatic
 ******************************************************************************/
extern void components_OnOffTest_testOn_Automatic_testOn (void);



#endif /* _ASD_COMPONENTS_ONOFFTEST_TESTON_AUTOMATIC_H_ */
