/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_DetectCurrentVelocityTest_resetCorrectV_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 15:05:58 Uhr
*
* @brief   "components_DetectCurrentVelocityTest_resetCorrectV>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_DetectCurrentVelocityTest_resetCorrectV_Automatic.h"
#include "ACC_Unit_Test_Automatic.h"
#include "assertLib_Assert_Impl.h"
#include "components_Globals_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_DetectCurrentVelocityTest_resetCorrectV_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'components_DetectCurrentVelocityTest_resetCorrectV'
 * data set:.....................................'COMPONENTS_DETECTCURRENTVELOCITYTEST_RESETCORRECTV_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_DetectCurrentVelocityTest_resetCorrectV_Automatic_RAM_SUBSTRUCT components_DetectCurrentVelocityTest_resetCorrectV_RAM = {
   /* struct element:'components_DetectCurrentVelocityTest_resetCorrectV_RAM.v' (modeled as:'v.components_DetectCurrentVelocityTest_resetCorrectV') */
   10.0F,
   /* substruct: components_DetectCurrentVelocityTest_resetCorrectV_RAM.dcv (modeled as:'dcv.components_DetectCurrentVelocityTest_resetCorrectV') */
   {
      /* struct element:'components_DetectCurrentVelocityTest_resetCorrectV_RAM.dcv.v_buffer' (modeled as:'v_buffer.dcv.components_DetectCurrentVelocityTest_resetCorrectV') */
      0.0F,
      /* struct element:'components_DetectCurrentVelocityTest_resetCorrectV_RAM.dcv.acc_status_old' (modeled as:'acc_status_old.dcv.components_DetectCurrentVelocityTest_resetCorrectV') */
      false,
      /* struct element:'components_DetectCurrentVelocityTest_resetCorrectV_RAM.dcv.status_old' (modeled as:'status_old.dcv.components_DetectCurrentVelocityTest_resetCorrectV') */
      false
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_DetectCurrentVelocityTest_resetCorrectV_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'components_DetectCurrentVelocityTest_resetCorrectV'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_DetectCurrentVelocityTest_resetCorrectV'
 * data set:.....................................'COMPONENTS_DETECTCURRENTVELOCITYTEST_RESETCORRECTV_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct components_DetectCurrentVelocityTest_resetCorrectV_Automatic components_DetectCurrentVelocityTest_resetCorrectV = {
   /* substruct: components_DetectCurrentVelocityTest_resetCorrectV.dcv (modeled as:'dcv.components_DetectCurrentVelocityTest_resetCorrectV') */
   {
      /* type descriptor pointer 'components_DetectCurrentVelocity_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_DetectCurrentVelocityTest_resetCorrectV_RAM.dcv
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'components_DetectCurrentVelocityTest_resetCorrectV'
 ******************************************************************************/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_DetectCurrentVelocityTest_resetCorrectV_Automatic_resetCorrectV'
 * ----------------------------------------------------------------------------
 * model name:...................................'resetCorrectV'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_DetectCurrentVelocityTest_resetCorrectV_Automatic_resetCorrectV (void)
{
   components_Globals_acc_status = true;
   components_DetectCurrentVelocity_Automatic_calc(&(components_DetectCurrentVelocityTest_resetCorrectV.dcv), components_Globals_acc_status, components_DetectCurrentVelocityTest_resetCorrectV_RAM.v);
   components_Globals_acc_status = false;
   components_DetectCurrentVelocity_Automatic_calc(&(components_DetectCurrentVelocityTest_resetCorrectV.dcv), components_Globals_acc_status, components_DetectCurrentVelocityTest_resetCorrectV_RAM.v);
   components_DetectCurrentVelocityTest_resetCorrectV_RAM.v = 12.0F;
   components_Globals_acc_status = true;
   components_DetectCurrentVelocity_Automatic_calc(&(components_DetectCurrentVelocityTest_resetCorrectV.dcv), components_Globals_acc_status, components_DetectCurrentVelocityTest_resetCorrectV_RAM.v);
   ASSERT_NEAR((float64)components_DetectCurrentVelocity_Automatic_getBuffer(&(components_DetectCurrentVelocityTest_resetCorrectV.dcv)), (float64)components_DetectCurrentVelocityTest_resetCorrectV_RAM.v, 0.1);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_DetectCurrentVelocityTest_resetCorrectV_Automatic_resetCorrectV'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



