#ifndef _ASD_COMPONENTS_ACCFEEDBACK_AUTOMATIC_H_
#define _ASD_COMPONENTS_ACCFEEDBACK_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_AccFeedback_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 15:05:58 Uhr
*
* @brief   "components_AccFeedback>>Automatic (module code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "chartab.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_AccFeedback_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct components_AccFeedback_Automatic_CAL_MEM_SUBSTRUCT {
   float32 c;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_AccFeedback_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_AccFeedback_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_AccFeedback_Automatic_RAM_SUBSTRUCT {
   float32 duration;
   uint8 acc_status_old;
   uint8 feedback;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_AccFeedback_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'components_AccFeedback_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct components_AccFeedback_Automatic {
   const volatile struct components_AccFeedback_Automatic_CAL_MEM_SUBSTRUCT * components_AccFeedback_Automatic_CAL_MEM;
   struct components_AccFeedback_Automatic_RAM_SUBSTRUCT * components_AccFeedback_Automatic_RAM;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'components_AccFeedback_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ...........components_AccFeedback_Automatic */
#define _components_AccFeedback_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class components_AccFeedback_Automatic
 ******************************************************************************/
extern void components_AccFeedback_Automatic_calc (
               const struct components_AccFeedback_Automatic * self,
   /* IN    */ const float32                                   my_dT
   );



#endif /* _ASD_COMPONENTS_ACCFEEDBACK_AUTOMATIC_H_ */
