#ifndef _ASD_COMPONENTS_FUSITEST_TESTFUSI3_AUTOMATIC_H_
#define _ASD_COMPONENTS_FUSITEST_TESTFUSI3_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_FuSiTest_testFuSi3_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 15:05:58 Uhr
*
* @brief   "components_FuSiTest_testFuSi3>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "chartab.h"
#include "components_FuSi_Automatic.h"


/* component structure for module COMPONENTS_FUSITEST_TESTFUSI3_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ....components_FuSiTest_testFuSi3_Automatic */
#define _components_FuSiTest_testFuSi3_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by module components_FuSiTest_testFuSi3_Automatic
 ******************************************************************************/
extern void components_FuSiTest_testFuSi3_Automatic_testFuSi3 (void);



#endif /* _ASD_COMPONENTS_FUSITEST_TESTFUSI3_AUTOMATIC_H_ */
