/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_AccFeedback_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 15:05:58 Uhr
*
* @brief   "components_AccFeedback>>Automatic (module code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_AccFeedback_Automatic.h"
#include "components_Globals_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/





/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_AccFeedback_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_AccFeedback_Automatic_calc (
               const struct components_AccFeedback_Automatic * self,
   /* IN    */ const float32                                   my_dT
   )
{
   if ((!components_Globals_acc_status) && (self->components_AccFeedback_Automatic_RAM->acc_status_old))
   {
      components_Globals_acc_feedback = true;
   } /* end if */
   self->components_AccFeedback_Automatic_RAM->acc_status_old = components_Globals_acc_status;
   if (components_Globals_acc_feedback)
   {
      self->components_AccFeedback_Automatic_RAM->duration = my_dT + self->components_AccFeedback_Automatic_RAM->duration;
   } /* end if */
   if (self->components_AccFeedback_Automatic_RAM->duration >= 3.0F)
   {
      components_Globals_acc_feedback = false;
      self->components_AccFeedback_Automatic_RAM->duration = 0.0F;
   } /* end if */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_AccFeedback_Automatic_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



