/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_FuSiTest_testFuSi1_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 15:05:58 Uhr
*
* @brief   "components_FuSiTest_testFuSi1>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_FuSiTest_testFuSi1_Automatic.h"
#include "ACC_Unit_Test_Automatic.h"
#include "assertLib_Assert_Impl.h"
#include "components_Globals_Automatic.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_FuSiTest_testFuSi1'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_FuSiTest_testFuSi1_Automatic_testFuSi1'
 * ----------------------------------------------------------------------------
 * model name:...................................'testFuSi1'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_FuSiTest_testFuSi1_Automatic_testFuSi1 (void)
{
   components_Globals_acc_status = true;
   components_FuSi_Automatic_crash_calc(&(components_Globals_acc_status), true);
   ASSERT_FALSE(components_Globals_acc_status);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_FuSiTest_testFuSi1_Automatic_testFuSi1'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



