/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_AccFeedbackTest_enableFeedbackTest_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 14:49:57 Uhr
*
* @brief   "components_AccFeedbackTest_enableFeedbackTest>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_AccFeedbackTest_enableFeedbackTest_Automatic.h"
#include "ACC_Unit_Test_Automatic.h"
#include "assertLib_Assert_Impl.h"
#include "components_Globals_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_AccFeedbackTest_enableFeedbackTest_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'components_AccFeedbackTest_enableFeedbackTest'
 * data set:.....................................'COMPONENTS_ACCFEEDBACKTEST_ENABLEFEEDBACKTEST_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const volatile struct components_AccFeedbackTest_enableFeedbackTest_Automatic_CAL_MEM_SUBSTRUCT components_AccFeedbackTest_enableFeedbackTest_CAL_MEM = {
   /* substruct: components_AccFeedbackTest_enableFeedbackTest_CAL_MEM.AccF (modeled as:'AccF.components_AccFeedbackTest_enableFeedbackTest') */
   {
      /* struct element:'components_AccFeedbackTest_enableFeedbackTest_CAL_MEM.AccF.c' (modeled as:'c.AccF.components_AccFeedbackTest_enableFeedbackTest') */
      0.0F
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_AccFeedbackTest_enableFeedbackTest_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_AccFeedbackTest_enableFeedbackTest_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'components_AccFeedbackTest_enableFeedbackTest'
 * data set:.....................................'COMPONENTS_ACCFEEDBACKTEST_ENABLEFEEDBACKTEST_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_AccFeedbackTest_enableFeedbackTest_Automatic_RAM_SUBSTRUCT components_AccFeedbackTest_enableFeedbackTest_RAM = {
   /* struct element:'components_AccFeedbackTest_enableFeedbackTest_RAM.test_dT' (modeled as:'test_dT.components_AccFeedbackTest_enableFeedbackTest') */
   0.0F,
   /* substruct: components_AccFeedbackTest_enableFeedbackTest_RAM.AccF (modeled as:'AccF.components_AccFeedbackTest_enableFeedbackTest') */
   {
      /* struct element:'components_AccFeedbackTest_enableFeedbackTest_RAM.AccF.duration' (modeled as:'duration.AccF.components_AccFeedbackTest_enableFeedbackTest') */
      0.0F,
      /* struct element:'components_AccFeedbackTest_enableFeedbackTest_RAM.AccF.acc_status_old' (modeled as:'acc_status_old.AccF.components_AccFeedbackTest_enableFeedbackTest') */
      false,
      /* struct element:'components_AccFeedbackTest_enableFeedbackTest_RAM.AccF.feedback' (modeled as:'feedback.AccF.components_AccFeedbackTest_enableFeedbackTest') */
      false
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_AccFeedbackTest_enableFeedbackTest_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'components_AccFeedbackTest_enableFeedbackTest'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_AccFeedbackTest_enableFeedbackTest'
 * data set:.....................................'COMPONENTS_ACCFEEDBACKTEST_ENABLEFEEDBACKTEST_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct components_AccFeedbackTest_enableFeedbackTest_Automatic components_AccFeedbackTest_enableFeedbackTest = {
   /* substruct: components_AccFeedbackTest_enableFeedbackTest.AccF (modeled as:'AccF.components_AccFeedbackTest_enableFeedbackTest') */
   {
      /* type descriptor pointer 'components_AccFeedback_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_AccFeedbackTest_enableFeedbackTest_CAL_MEM.AccF,
      /* type descriptor pointer 'components_AccFeedback_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_AccFeedbackTest_enableFeedbackTest_RAM.AccF
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'components_AccFeedbackTest_enableFeedbackTest'
 ******************************************************************************/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_AccFeedbackTest_enableFeedbackTest_Automatic_enableFeedbackTest'
 * ----------------------------------------------------------------------------
 * model name:...................................'enableFeedbackTest'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_AccFeedbackTest_enableFeedbackTest_Automatic_enableFeedbackTest (void)
{
   components_Globals_acc_status = true;
   components_Globals_acc_feedback = false;
   components_AccFeedback_Automatic_calc(&(components_AccFeedbackTest_enableFeedbackTest.AccF), 0.0F);
   components_Globals_acc_status = false;
   components_AccFeedback_Automatic_calc(&(components_AccFeedbackTest_enableFeedbackTest.AccF), 1.0F);
   ASSERT_TRUE(components_Globals_acc_feedback);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_AccFeedbackTest_enableFeedbackTest_Automatic_enableFeedbackTest'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



