#ifndef _ASD_COMPONENTS_FUSI_AUTOMATIC_H_
#define _ASD_COMPONENTS_FUSI_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_FuSi_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 15:05:58 Uhr
*
* @brief   "components_FuSi>>Automatic (module code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "chartab.h"


/* component structure for class COMPONENTS_FUSI_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ..................components_FuSi_Automatic */
#define _components_FuSi_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class components_FuSi_Automatic
 ******************************************************************************/
extern void components_FuSi_Automatic_crash_calc (
   /* INOUT */ uint8 *     acc_status,
   /* IN    */ const uint8 crash_detected
   );



#endif /* _ASD_COMPONENTS_FUSI_AUTOMATIC_H_ */
