/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_SteckeTest_testStecke1_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 15:05:58 Uhr
*
* @brief   "components_SteckeTest_testStecke1>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_SteckeTest_testStecke1_Automatic.h"
#include "ACC_Unit_Test_Automatic.h"
#include "assertLib_Assert_Impl.h"
#include "interfaces_interfaces_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_SteckeTest_testStecke1_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'components_SteckeTest_testStecke1'
 * data set:.....................................'COMPONENTS_STECKETEST_TESTSTECKE1_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const volatile struct components_SteckeTest_testStecke1_Automatic_CAL_MEM_SUBSTRUCT components_SteckeTest_testStecke1_CAL_MEM = {
   /* substruct: components_SteckeTest_testStecke1_CAL_MEM.s (modeled as:'s.components_SteckeTest_testStecke1') */
   {
      /* struct element:'components_SteckeTest_testStecke1_CAL_MEM.s.AirFriction' (modeled as:'AirFriction.s.components_SteckeTest_testStecke1') */
      {
         6U,
         {
            0.0F, 30.0F, 60.0F, 90.0F, 120.0F, 150.0F
         },
         {
            0.0F, -0.1F, -0.2F, -0.4F, -0.8F, -1.6F
         }
      },
      /* struct element:'components_SteckeTest_testStecke1_CAL_MEM.s.BrakeMomentum' (modeled as:'BrakeMomentum.s.components_SteckeTest_testStecke1') */
      {
         6U,
         {
            0.0F, 1.0F, 40.0F, 60.0F, 80.0F, 100.0F
         },
         {
            0.0F, 0.0F, -1.0F, -2.0F, -3.0F, -4.0F
         }
      },
      /* struct element:'components_SteckeTest_testStecke1_CAL_MEM.s.EngineMomentum' (modeled as:'EngineMomentum.s.components_SteckeTest_testStecke1') */
      {
         6U,
         6U,
         {
            0.0F, 5.0F, 20.0F, 60.0F, 80.0F, 100.0F
         },
         {
            0.0F, 30.0F, 60.0F, 90.0F, 150.0F, 200.0F
         },
         {
            0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
            0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
            0.85F, 0.6F, 0.3F, 0.0F, 0.0F, 0.0F,
            3.15F, 2.35F, 1.55F, 0.8F, 0.4F, 0.0F,
            4.5F, 3.6F, 2.7F, 1.5F, 0.9F, 0.0F,
            5.0F, 4.5F, 3.8F, 2.8F, 1.9F, 0.0F
         }
      },
      /* struct element:'components_SteckeTest_testStecke1_CAL_MEM.s.Landscape' (modeled as:'Landscape.s.components_SteckeTest_testStecke1') */
      {
         20U,
         {
            0.0F, 100.0F, 145.5657F, 202.53F, 221.52F, 240.0F, 259.49F, 300.0F, 350.0F,
            400.0F, 450.0F, 500.0F, 600.0F, 700.0F, 750.0F, 800.0F, 810.0F, 850.0F, 900.0F,
            1000.0F
         },
         {
            0.0F, 4.0F, 7.125F, 10.375F, 10.75F, 10.5F, 9.0F, 5.375F, 2.625F, 0.625F, 1.25F,
            0.625F, 0.0F, 0.0F, 1.375F, 0.75F, 0.375F, 0.625F, 0.0F, 0.0F
         }
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_SteckeTest_testStecke1_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_SteckeTest_testStecke1_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'components_SteckeTest_testStecke1'
 * data set:.....................................'COMPONENTS_STECKETEST_TESTSTECKE1_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_SteckeTest_testStecke1_Automatic_RAM_SUBSTRUCT components_SteckeTest_testStecke1_RAM = {
   /* struct element:'components_SteckeTest_testStecke1_RAM.i' (modeled as:'i.components_SteckeTest_testStecke1') */
   0,
   /* struct element:'components_SteckeTest_testStecke1_RAM.s1' (modeled as:'s1.components_SteckeTest_testStecke1') */
   0.0F,
   /* struct element:'components_SteckeTest_testStecke1_RAM.s2' (modeled as:'s2.components_SteckeTest_testStecke1') */
   0.0F,
   /* substruct: components_SteckeTest_testStecke1_RAM.s (modeled as:'s.components_SteckeTest_testStecke1') */
   {
      /* struct element:'components_SteckeTest_testStecke1_RAM.s.TrackSize' (modeled as:'TrackSize.s.components_SteckeTest_testStecke1') */
      0.0F,
      /* struct element:'components_SteckeTest_testStecke1_RAM.s.dh' (modeled as:'dh.s.components_SteckeTest_testStecke1') */
      0.0F,
      /* struct element:'components_SteckeTest_testStecke1_RAM.s.ds' (modeled as:'ds.s.components_SteckeTest_testStecke1') */
      0.0F,
      /* struct element:'components_SteckeTest_testStecke1_RAM.s.h' (modeled as:'h.s.components_SteckeTest_testStecke1') */
      0.0F,
      /* struct element:'components_SteckeTest_testStecke1_RAM.s.momentum' (modeled as:'momentum.s.components_SteckeTest_testStecke1') */
      0.0F,
      /* struct element:'components_SteckeTest_testStecke1_RAM.s.s' (modeled as:'s.s.components_SteckeTest_testStecke1') */
      0.0F
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_SteckeTest_testStecke1_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'components_SteckeTest_testStecke1'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_SteckeTest_testStecke1'
 * data set:.....................................'COMPONENTS_STECKETEST_TESTSTECKE1_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct components_SteckeTest_testStecke1_Automatic components_SteckeTest_testStecke1 = {
   /* substruct: components_SteckeTest_testStecke1.s (modeled as:'s.components_SteckeTest_testStecke1') */
   {
      /* type descriptor pointer 'components_Stecke_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_SteckeTest_testStecke1_CAL_MEM.s,
      /* type descriptor pointer 'components_Stecke_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_SteckeTest_testStecke1_RAM.s
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'components_SteckeTest_testStecke1'
 ******************************************************************************/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_SteckeTest_testStecke1_Automatic_testStecke1'
 * ----------------------------------------------------------------------------
 * model name:...................................'testStecke1'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_SteckeTest_testStecke1_Automatic_testStecke1 (void)
{
   components_SteckeTest_testStecke1_RAM.s.s = 0.0F;
   components_SteckeTest_testStecke1_RAM.s1 = components_SteckeTest_testStecke1_RAM.s.s;
   while (components_SteckeTest_testStecke1_RAM.i < 100)
   {
      components_SteckeTest_testStecke1_RAM.i
         = ((components_SteckeTest_testStecke1_RAM.i <= 2147483646L /* always true */) ? (components_SteckeTest_testStecke1_RAM.i + 1) : 2147483647L);
      components_Stecke_Automatic_vCar(&(components_SteckeTest_testStecke1.s), 0.0F, 100.0F, 1.0F);
   } /* end while */
   components_SteckeTest_testStecke1_RAM.s2 = components_SteckeTest_testStecke1_RAM.s.s;
   ASSERT_GT((float64)components_SteckeTest_testStecke1_RAM.s2, (float64)components_SteckeTest_testStecke1_RAM.s1);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_SteckeTest_testStecke1_Automatic_testStecke1'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



