#ifndef _ASD_ACC_UNITTEST_AUTOMATIC_H_
#define _ASD_ACC_UNITTEST_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    ACC_UnitTest_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    28.02.2019 10:07:43
*
* @brief   "ACC_UnitTest>>Automatic (project code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "assertLib_Assert_Impl.h"
#include "components_Component_Automatic.h"


/* component structure for project ACC_UNITTEST_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .....................ACC_UnitTest_Automatic */
#define _ACC_UnitTest_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by project ACC_UnitTest_Automatic
 ******************************************************************************/



#endif /* _ASD_ACC_UNITTEST_AUTOMATIC_H_ */
