#ifndef _ASD_ACC_UNITTEST_AUTOMATIC_H_
#define _ASD_ACC_UNITTEST_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    ACC_UnitTest_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
<<<<<<< HEAD
* @date    01.03.2019 11:04:59 Uhr
=======
* @date    01.03.2019 09:59:36 Uhr
>>>>>>> 006cb0adc89c783217d313dcf9d2514c7d2d75da
*
* @brief   "ACC_UnitTest>>Automatic (project code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "assertLib_Assert_Impl.h"
#include "components_circleTest_Automatic.h"
#include "components_Component_Automatic.h"
<<<<<<< HEAD
#include "components_FuSi_Automatic.h"
#include "components_FuSiTest_Automatic.h"
#include "components_Globals_Automatic.h"
#include "components_OnOff_Automatic.h"
#include "components_OnOffTest_Automatic.h"
#include "interfaces_interfaces_Automatic.h"
=======
>>>>>>> 006cb0adc89c783217d313dcf9d2514c7d2d75da


/* component structure for project ACC_UNITTEST_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .....................ACC_UnitTest_Automatic */
#define _ACC_UnitTest_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by project ACC_UnitTest_Automatic
 ******************************************************************************/



#endif /* _ASD_ACC_UNITTEST_AUTOMATIC_H_ */
