/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    assertLib_Assert_Impl.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    01.03.2019 12:46:12 Uhr
*
* @brief   "assertLib_Assert>>Impl (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "assertLib_Assert_Impl.h"
/******************************************************************************
 * BEGIN: source code of a single instance class
 ******************************************************************************/


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'assertLib_Assert'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/
/*method "assertBetween" not generated due to Implementation option "Generate method body" turned off */
/*method "assertDoubleEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "assertEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "assertFalse" not generated due to Implementation option "Generate method body" turned off */
/*method "assertFloatEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "assertGreaterThan" not generated due to Implementation option "Generate method body" turned off */
/*method "assertGreaterThanOrEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "assertIntBetween" not generated due to Implementation option "Generate method body" turned off */
/*method "assertIntEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "assertIntGreaterThan" not generated due to Implementation option "Generate method body" turned off */
/*method "assertIntGreaterThanOrEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "assertIntLessThan" not generated due to Implementation option "Generate method body" turned off */
/*method "assertIntLessThanOrEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "assertIntNotEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "assertLessThan" not generated due to Implementation option "Generate method body" turned off */
/*method "assertLessThanOrEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "assertNear" not generated due to Implementation option "Generate method body" turned off */
/*method "assertNotEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "assertTrue" not generated due to Implementation option "Generate method body" turned off */
/*method "assertUIntBetween" not generated due to Implementation option "Generate method body" turned off */
/*method "assertUIntEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "assertUIntGreaterThan" not generated due to Implementation option "Generate method body" turned off */
/*method "assertUIntGreaterThanOrEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "assertUIntLessThan" not generated due to Implementation option "Generate method body" turned off */
/*method "assertUIntLessThanOrEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "assertUIntNotEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "expectBetween" not generated due to Implementation option "Generate method body" turned off */
/*method "expectDoubleEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "expectEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "expectFalse" not generated due to Implementation option "Generate method body" turned off */
/*method "expectFloatEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "expectGreaterThan" not generated due to Implementation option "Generate method body" turned off */
/*method "expectGreaterThanOrEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "expectIntBetween" not generated due to Implementation option "Generate method body" turned off */
/*method "expectIntEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "expectIntGreaterThan" not generated due to Implementation option "Generate method body" turned off */
/*method "expectIntGreaterThanOrEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "expectIntLessThan" not generated due to Implementation option "Generate method body" turned off */
/*method "expectIntLessThanOrEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "expectIntNotEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "expectLessThan" not generated due to Implementation option "Generate method body" turned off */
/*method "expectLessThanOrEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "expectNear" not generated due to Implementation option "Generate method body" turned off */
/*method "expectNotEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "expectTrue" not generated due to Implementation option "Generate method body" turned off */
/*method "expectUIntBetween" not generated due to Implementation option "Generate method body" turned off */
/*method "expectUIntEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "expectUIntGreaterThan" not generated due to Implementation option "Generate method body" turned off */
/*method "expectUIntGreaterThanOrEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "expectUIntLessThan" not generated due to Implementation option "Generate method body" turned off */
/*method "expectUIntLessThanOrEqual" not generated due to Implementation option "Generate method body" turned off */
/*method "expectUIntNotEqual" not generated due to Implementation option "Generate method body" turned off */

/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



