/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_FuSiTest_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 11:24:16 Uhr
*
* @brief   "components_FuSiTest>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_FuSiTest_Automatic.h"
#include "ACC_UnitTest_Automatic.h"
#include "assertLib_Assert_Impl.h"
#include "components_FuSi_Automatic.h"
#include "components_Globals_Automatic.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_FuSiTest'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_FuSiTest_Automatic_testFuSi'
 * ----------------------------------------------------------------------------
 * model name:...................................'testFuSi'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_FuSiTest_Automatic_testFuSi (void)
{
   components_Globals_acc_status = true;
   components_FuSi_Automatic_onCrash(true);
   ASSERT_FALSE(components_Globals_acc_status);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_FuSiTest_Automatic_testFuSi'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



