#ifndef _ASD_COMPONENTS_ONOFFTEST_TESTSTOP_AUTOMATIC_H_
#define _ASD_COMPONENTS_ONOFFTEST_TESTSTOP_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_OnOffTest_testStop_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    01.03.2019 12:46:12 Uhr
*
* @brief   "components_OnOffTest_testStop>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "components_OnOff_Automatic.h"


/* component structure for module COMPONENTS_ONOFFTEST_TESTSTOP_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ....components_OnOffTest_testStop_Automatic */
#define _components_OnOffTest_testStop_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by module components_OnOffTest_testStop_Automatic
 ******************************************************************************/
extern void components_OnOffTest_testStop_Automatic_testStop (void);



#endif /* _ASD_COMPONENTS_ONOFFTEST_TESTSTOP_AUTOMATIC_H_ */
