/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_FuSi_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 13:20:30 Uhr
*
* @brief   "components_FuSi>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_FuSi_Automatic.h"
#include "interfaces_interfaces_Automatic.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_FuSi'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_FuSi_Automatic_crash_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'crash_calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

uint8 components_FuSi_Automatic_crash_calc (
   /* INOUT */ uint8 *     acc_status,
   /* IN    */ const uint8 crash_detected
   )
{
   if (crash_detected)
   {
      (*acc_status) = false;
   } /* end if */
   return (*acc_status);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_FuSi_Automatic_crash_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



