#ifndef _ASD_COMPONENTS_COMPONENT_AUTOMATIC_H_
#define _ASD_COMPONENTS_COMPONENT_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Component_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    01.03.2019 12:46:12 Uhr
*
* @brief   "components_Component>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/* component structure for module COMPONENTS_COMPONENT_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .............components_Component_Automatic */
#define _components_Component_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by module components_Component_Automatic
 ******************************************************************************/
extern void components_Component_Automatic_pass (void);



#endif /* _ASD_COMPONENTS_COMPONENT_AUTOMATIC_H_ */
