/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_HillsValleysTest_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 13:20:30 Uhr
*
* @brief   "components_HillsValleysTest>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_HillsValleysTest_Automatic.h"
#include "ACC_UnitTest_Automatic.h"
#include "assertLib_Assert_Impl.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_HillsValleysTest_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'components_HillsValleysTest'
 * data set:.....................................'COMPONENTS_HILLSVALLEYSTEST_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const volatile struct components_HillsValleysTest_Automatic_CAL_MEM_SUBSTRUCT components_HillsValleysTest_CAL_MEM = {
   /* substruct: components_HillsValleysTest_CAL_MEM._stecke (modeled as:'_stecke.components_HillsValleysTest') */
   {
      /* struct element:'components_HillsValleysTest_CAL_MEM._stecke.TrackSize' (modeled as:'TrackSize._stecke.components_HillsValleysTest') */
      1000.0F,
      /* struct element:'components_HillsValleysTest_CAL_MEM._stecke.AirFriction' (modeled as:'AirFriction._stecke.components_HillsValleysTest') */
      {
         6U,
         {
            0.0F, 30.0F, 60.0F, 90.0F, 120.0F, 150.0F
         },
         {
            0.0F, -0.1F, -0.2F, -0.4F, -0.8F, -1.6F
         }
      },
      /* struct element:'components_HillsValleysTest_CAL_MEM._stecke.BrakeMomentum' (modeled as:'BrakeMomentum._stecke.components_HillsValleysTest') */
      {
         6U,
         {
            0.0F, 1.0F, 40.0F, 60.0F, 80.0F, 100.0F
         },
         {
            0.0F, 0.0F, -1.0F, -2.0F, -3.0F, -4.0F
         }
      },
      /* struct element:'components_HillsValleysTest_CAL_MEM._stecke.EngineMomentum' (modeled as:'EngineMomentum._stecke.components_HillsValleysTest') */
      {
         6U,
         6U,
         {
            0.0F, 5.0F, 20.0F, 60.0F, 80.0F, 100.0F
         },
         {
            0.0F, 30.0F, 60.0F, 90.0F, 150.0F, 200.0F
         },
         {
            0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
            0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
            0.85F, 0.6F, 0.3F, 0.0F, 0.0F, 0.0F,
            3.15F, 2.35F, 1.55F, 0.8F, 0.4F, 0.0F,
            4.5F, 3.6F, 2.7F, 1.5F, 0.9F, 0.0F,
            5.0F, 4.5F, 3.8F, 2.8F, 1.9F, 0.0F
         }
      },
      /* struct element:'components_HillsValleysTest_CAL_MEM._stecke.Landscape' (modeled as:'Landscape._stecke.components_HillsValleysTest') */
      {
         20U,
         {
            0.0F, 100.0F, 145.5657F, 202.53F, 221.52F, 240.0F, 259.49F, 300.0F, 350.0F,
            400.0F, 450.0F, 500.0F, 600.0F, 700.0F, 750.0F, 800.0F, 810.0F, 850.0F, 900.0F,
            1000.0F
         },
         {
            0.0F, 4.0F, 7.125F, 10.375F, 10.75F, 10.5F, 9.0F, 5.375F, 2.625F, 0.625F, 1.25F,
            0.625F, 0.0F, 0.0F, 1.375F, 0.75F, 0.375F, 0.625F, 0.0F, 0.0F
         }
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_HillsValleysTest_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_HillsValleysTest_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'components_HillsValleysTest'
 * data set:.....................................'COMPONENTS_HILLSVALLEYSTEST_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_HillsValleysTest_Automatic_RAM_SUBSTRUCT components_HillsValleysTest_RAM = {
   /* substruct: components_HillsValleysTest_RAM._stecke (modeled as:'_stecke.components_HillsValleysTest') */
   {
      /* struct element:'components_HillsValleysTest_RAM._stecke.dh' (modeled as:'dh._stecke.components_HillsValleysTest') */
      0.0F,
      /* struct element:'components_HillsValleysTest_RAM._stecke.ds' (modeled as:'ds._stecke.components_HillsValleysTest') */
      0.0F,
      /* struct element:'components_HillsValleysTest_RAM._stecke.h' (modeled as:'h._stecke.components_HillsValleysTest') */
      0.0F,
      /* struct element:'components_HillsValleysTest_RAM._stecke.momentum' (modeled as:'momentum._stecke.components_HillsValleysTest') */
      0.0F,
      /* struct element:'components_HillsValleysTest_RAM._stecke.s' (modeled as:'s._stecke.components_HillsValleysTest') */
      0.0F
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_HillsValleysTest_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'components_HillsValleysTest'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_HillsValleysTest'
 * data set:.....................................'COMPONENTS_HILLSVALLEYSTEST_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct components_HillsValleysTest_Automatic components_HillsValleysTest = {
   /* substruct: components_HillsValleysTest._stecke (modeled as:'_stecke.components_HillsValleysTest') */
   {
      /* type descriptor pointer 'components_Stecke_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_HillsValleysTest_CAL_MEM._stecke,
      /* type descriptor pointer 'components_Stecke_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_HillsValleysTest_RAM._stecke
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'components_HillsValleysTest'
 ******************************************************************************/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_HillsValleysTest_Automatic_SlopeTest'
 * ----------------------------------------------------------------------------
 * model name:...................................'SlopeTest'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_HillsValleysTest_Automatic_SlopeTest (void)
{
   /* user defined local variables */
   float32 first;
   float32 h_first;
   float32 h_second;
   float32 second;
   float32 slope;
   /* temp. variables */
   float32 _t1real32;
   float32 _t2real32;

   first = 0.0F;
   second = 10.0F;
   while (second <= 1000.0F)
   {
      h_first
         = components_Stecke_Automatic_getHeight(&(components_HillsValleysTest._stecke), first);
      h_second
         = components_Stecke_Automatic_getHeight(&(components_HillsValleysTest._stecke), second);
      _t1real32 = second - first;
      _t2real32 = h_second - h_first;
      _t2real32 = ((_t2real32 > 0.0F) ? _t2real32 : -_t2real32);
      slope = ((_t1real32 == 0.0F) ? _t2real32 : (_t2real32 / _t1real32));
      ASSERT_TRUE(slope <= 0.2F);
      first = first + 10.0F;
      second = second + 10.0F;
   } /* end while */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_HillsValleysTest_Automatic_SlopeTest'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



