/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_circleTest_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    01.03.2019 09:59:36 Uhr
*
* @brief   "components_circleTest>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_circleTest_Automatic.h"
#include "ACC_UnitTest_Automatic.h"
#include "assertLib_Assert_Impl.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_circleTest'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_circleTest_Automatic_pass'
 * ----------------------------------------------------------------------------
 * model name:...................................'pass'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_circleTest_Automatic_pass (void)
{
   ASSERT_TRUE(true);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_circleTest_Automatic_pass'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



