/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_FuSiTest_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 13:20:30 Uhr
*
* @brief   "components_FuSiTest>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_FuSiTest_Automatic.h"
#include "ACC_UnitTest_Automatic.h"
#include "assertLib_Assert_Impl.h"
#include "components_FuSi_Automatic.h"
#include "interfaces_interfaces_Automatic.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_FuSiTest'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_FuSiTest_Automatic_testFuSi1'
 * ----------------------------------------------------------------------------
 * model name:...................................'testFuSi1'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_FuSiTest_Automatic_testFuSi1 (void)
{
   /* user defined local variables */
   uint8 ergebnis;

   ergebnis = false;
   ergebnis = components_FuSi_Automatic_crash_calc(&(ergebnis), false);
   ASSERT_FALSE(ergebnis);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_FuSiTest_Automatic_testFuSi1'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_FuSiTest_Automatic_testFuSi2'
 * ----------------------------------------------------------------------------
 * model name:...................................'testFuSi2'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_FuSiTest_Automatic_testFuSi2 (void)
{
   /* user defined local variables */
   uint8 ergebnis;

   ergebnis = false;
   ergebnis = components_FuSi_Automatic_crash_calc(&(ergebnis), true);
   ASSERT_FALSE(ergebnis);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_FuSiTest_Automatic_testFuSi2'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_FuSiTest_Automatic_testFuSi3'
 * ----------------------------------------------------------------------------
 * model name:...................................'testFuSi3'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_FuSiTest_Automatic_testFuSi3 (void)
{
   /* user defined local variables */
   uint8 ergebnis;

   ergebnis = true;
   ergebnis = components_FuSi_Automatic_crash_calc(&(ergebnis), false);
   ASSERT_TRUE(ergebnis);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_FuSiTest_Automatic_testFuSi3'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_FuSiTest_Automatic_testFuSi4'
 * ----------------------------------------------------------------------------
 * model name:...................................'testFuSi4'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_FuSiTest_Automatic_testFuSi4 (void)
{
   /* user defined local variables */
   uint8 ergebnis;

   ergebnis = true;
   ergebnis = components_FuSi_Automatic_crash_calc(&(ergebnis), true);
   ASSERT_FALSE(ergebnis);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_FuSiTest_Automatic_testFuSi4'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



