#ifndef _ASD_COMPONENTS_ONOFF_AUTOMATIC_H_
#define _ASD_COMPONENTS_ONOFF_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_OnOff_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 11:24:16 Uhr
*
* @brief   "components_OnOff>>Automatic (module code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/* component structure for class COMPONENTS_ONOFF_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .................components_OnOff_Automatic */
#define _components_OnOff_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class components_OnOff_Automatic
 ******************************************************************************/
extern uint8 components_OnOff_Automatic_onoff (
   /* IN    */ const float32 v,
   /* IN    */ const uint8   request
   );



#endif /* _ASD_COMPONENTS_ONOFF_AUTOMATIC_H_ */
