/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Stecke_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 13:20:30 Uhr
*
* @brief   "components_Stecke>>Automatic (module code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_Stecke_Automatic.h"
#include "components_Globals_Automatic.h"
#include "ESDL_Linear_Interpolation.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/





/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Stecke_Automatic_getHeight'
 * ----------------------------------------------------------------------------
 * model name:...................................'getHeight'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_Stecke_Automatic_getHeight (
               const struct components_Stecke_Automatic * self,
   /* IN    */ const float32                              at
   )
{
   return ESDL_Linear_CharTable1_getAt_r32r32(((&(self->components_Stecke_Automatic_CAL_MEM->Landscape)))->xSize, ((&(self->components_Stecke_Automatic_CAL_MEM->Landscape)))->xDist, ((&(self->components_Stecke_Automatic_CAL_MEM->Landscape)))->values, at);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Stecke_Automatic_getHeight'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Stecke_Automatic_getV'
 * ----------------------------------------------------------------------------
 * model name:...................................'getV'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_Stecke_Automatic_getV ( const struct components_Stecke_Automatic * self)
{
   return components_Globals_v;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Stecke_Automatic_getV'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Stecke_Automatic_vCar'
 * ----------------------------------------------------------------------------
 * model name:...................................'vCar'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_Stecke_Automatic_vCar (
               const struct components_Stecke_Automatic * self,
   /* IN    */ const float32                              brakeCtrl,
   /* IN    */ const float32                              powerCtrl,
   /* IN    */ const float32                              my_dT
   )
{
   if (self->components_Stecke_Automatic_RAM->s > self->components_Stecke_Automatic_CAL_MEM->TrackSize)
   {
      self->components_Stecke_Automatic_RAM->s = 0.0F;
   } /* end if */
   self->components_Stecke_Automatic_RAM->momentum
      = ESDL_Linear_CharTable2_getAt_r32r32r32(((&(self->components_Stecke_Automatic_CAL_MEM->EngineMomentum)))->xSize, ((&(self->components_Stecke_Automatic_CAL_MEM->EngineMomentum)))->xDist, ((&(self->components_Stecke_Automatic_CAL_MEM->EngineMomentum)))->ySize, ((&(self->components_Stecke_Automatic_CAL_MEM->EngineMomentum)))->yDist, ((&(self->components_Stecke_Automatic_CAL_MEM->EngineMomentum)))->values, powerCtrl, components_Globals_v);
   self->components_Stecke_Automatic_RAM->ds = (components_Globals_v * my_dT) / 3.6F;
   self->components_Stecke_Automatic_RAM->s
      = self->components_Stecke_Automatic_RAM->ds + self->components_Stecke_Automatic_RAM->s;
   self->components_Stecke_Automatic_RAM->dh
      = self->components_Stecke_Automatic_RAM->h - ESDL_Linear_CharTable1_getAt_r32r32(((&(self->components_Stecke_Automatic_CAL_MEM->Landscape)))->xSize, ((&(self->components_Stecke_Automatic_CAL_MEM->Landscape)))->xDist, ((&(self->components_Stecke_Automatic_CAL_MEM->Landscape)))->values, self->components_Stecke_Automatic_RAM->s);
   self->components_Stecke_Automatic_RAM->h
      = ESDL_Linear_CharTable1_getAt_r32r32(((&(self->components_Stecke_Automatic_CAL_MEM->Landscape)))->xSize, ((&(self->components_Stecke_Automatic_CAL_MEM->Landscape)))->xDist, ((&(self->components_Stecke_Automatic_CAL_MEM->Landscape)))->values, self->components_Stecke_Automatic_RAM->s);
   if (components_Globals_v < 0.0F)
   {
      components_Globals_v = 0.0F;
   } /* end if */
   components_Globals_v
      = ((ESDL_Linear_CharTable1_getAt_r32r32(((&(self->components_Stecke_Automatic_CAL_MEM->BrakeMomentum)))->xSize, ((&(self->components_Stecke_Automatic_CAL_MEM->BrakeMomentum)))->xDist, ((&(self->components_Stecke_Automatic_CAL_MEM->BrakeMomentum)))->values, brakeCtrl) + self->components_Stecke_Automatic_RAM->momentum + ESDL_Linear_CharTable1_getAt_r32r32(((&(self->components_Stecke_Automatic_CAL_MEM->AirFriction)))->xSize, ((&(self->components_Stecke_Automatic_CAL_MEM->AirFriction)))->xDist, ((&(self->components_Stecke_Automatic_CAL_MEM->AirFriction)))->values, components_Globals_v) + ((((self->components_Stecke_Automatic_RAM->ds == 0.0F) ? self->components_Stecke_Automatic_RAM->dh : (self->components_Stecke_Automatic_RAM->dh / self->components_Stecke_Automatic_RAM->ds))) * 9.81F)) * my_dT * 3.6F) + components_Globals_v;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Stecke_Automatic_vCar'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



