#ifndef _ASD_COMPONENTS_GLOBALS_AUTOMATIC_H_
#define _ASD_COMPONENTS_GLOBALS_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Globals_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    01.03.2019 11:04:59 Uhr
*
* @brief   "components_Globals>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/* component structure for module COMPONENTS_GLOBALS_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ...............components_Globals_Automatic */
#define _components_Globals_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by module components_Globals_Automatic
 ******************************************************************************/
extern uint8 components_Globals_acc_feedback;
extern uint8 components_Globals_acc_status;
extern uint8 components_Globals_acc_status_request;
extern float32 components_Globals_v;
extern float32 components_Globals_z;



#endif /* _ASD_COMPONENTS_GLOBALS_AUTOMATIC_H_ */
