#ifndef _ASD_COMPONENTS_CIRCLETEST_AUTOMATIC_H_
#define _ASD_COMPONENTS_CIRCLETEST_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_circleTest_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 11:24:16 Uhr
*
* @brief   "components_circleTest>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/* component structure for module COMPONENTS_CIRCLETEST_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ............components_circleTest_Automatic */
#define _components_circleTest_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by module components_circleTest_Automatic
 ******************************************************************************/
extern void components_circleTest_Automatic_pass (void);



#endif /* _ASD_COMPONENTS_CIRCLETEST_AUTOMATIC_H_ */
