#ifndef _ASD_COMPONENTS_FUSI_AUTOMATIC_H_
#define _ASD_COMPONENTS_FUSI_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_FuSi_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    01.03.2019 10:47:06 Uhr
*
* @brief   "components_FuSi>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/* component structure for module COMPONENTS_FUSI_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ..................components_FuSi_Automatic */
#define _components_FuSi_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by module components_FuSi_Automatic
 ******************************************************************************/
extern void components_FuSi_Automatic_onCrash (/* IN    */ const uint8 crash);
extern void components_FuSi_Automatic_calc (void);



#endif /* _ASD_COMPONENTS_FUSI_AUTOMATIC_H_ */
