/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_OnOffTest_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    01.03.2019 11:04:59 Uhr
*
* @brief   "components_OnOffTest>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_OnOffTest_Automatic.h"
#include "ACC_UnitTest_Automatic.h"
#include "assertLib_Assert_Impl.h"
#include "components_Globals_Automatic.h"
#include "components_OnOff_Automatic.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_OnOffTest'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_OnOffTest_Automatic_testOff'
 * ----------------------------------------------------------------------------
 * model name:...................................'testOff'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_OnOffTest_Automatic_testOff (void)
{
   components_Globals_v = 1.0F;
   components_OnOff_Automatic_calc();
   components_Globals_acc_status_request = false;
   ASSERT_FALSE(components_Globals_acc_status);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_OnOffTest_Automatic_testOff'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_OnOffTest_Automatic_testOffFailure'
 * ----------------------------------------------------------------------------
 * model name:...................................'testOffFailure'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_OnOffTest_Automatic_testOffFailure (void)
{
   components_Globals_acc_status = true;
   components_Globals_v = 0.0F;
   components_OnOff_Automatic_calc();
   components_Globals_acc_status_request = false;
   ASSERT_TRUE(components_Globals_acc_status);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_OnOffTest_Automatic_testOffFailure'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_OnOffTest_Automatic_testOn'
 * ----------------------------------------------------------------------------
 * model name:...................................'testOn'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_OnOffTest_Automatic_testOn (void)
{
   components_Globals_v = 1.0F;
   components_OnOff_Automatic_calc();
   components_Globals_acc_status_request = true;
   ASSERT_TRUE(components_Globals_acc_status);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_OnOffTest_Automatic_testOn'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_OnOffTest_Automatic_testOnFailure'
 * ----------------------------------------------------------------------------
 * model name:...................................'testOnFailure'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_OnOffTest_Automatic_testOnFailure (void)
{
   components_Globals_acc_status = false;
   components_Globals_v = 0.0F;
   components_OnOff_Automatic_calc();
   components_Globals_acc_status_request = true;
   ASSERT_FALSE(components_Globals_acc_status);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_OnOffTest_Automatic_testOnFailure'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



