#ifndef ESDL_MESSAGECOPY_H
#define ESDL_MESSAGECOPY_H

/**
  * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  * 
  * @file    esdl_messageCopy.h
  * 
  * @author  Generated by ASCET-DEVELOPER V7.4.0
  * 
<<<<<<< HEAD
  * @date    3/1/2019 11:4:59 AM
=======
  * @date    3/1/2019 9:59:37 AM
>>>>>>> 006cb0adc89c783217d313dcf9d2514c7d2d75da
  * 
  * @brief   Header file for message copy logic
  **/



#endif /* ESDL_MESSAGECOPY_H */
