#ifndef GLOBALH_H
#define GLOBALH_H
/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 * 
 * @file    globalH.h
 * 
 * @author  Generated by ASCET-DEVELOPER V7.4.0
 * 
 * @date    01.03.2019 11:03:59
 * 
 * @brief   this global header file supports pre-compiled header feature
 * 
 **/
#include "esdl.h"
#endif /* GLOBALH_H */
