/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    interfaces_interfaces_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 11:24:16 Uhr
*
* @brief   "interfaces_interfaces>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "interfaces_interfaces_Automatic.h"


/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'interfaces_interfaces'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/






/******************************************************************************
 * BEGIN: DEFINITION OF MESSAGES
 * ----------------------------------------------------------------------------
 * Total size is [bytes]:........................14
 * ---------------------------------------------------------------------------*/
/* messages of memory class:............................................'RAM' */
/* messages of size [bytes]:................................................4 */
/* modelled as 'interfaces_interfaces_brake' */
float32 interfaces_interfaces_brake = 0.0F;
/* modelled as 'interfaces_interfaces_power' */
float32 interfaces_interfaces_power = 0.0F;
/* modelled as 'interfaces_interfaces_v' */
float32 interfaces_interfaces_v = 0.0F;
/* messages of size [bytes]:................................................1 */
/* modelled as 'interfaces_interfaces_crash_detected' */
uint8 interfaces_interfaces_crash_detected = false;
/* modelled as 'interfaces_interfaces_plusButtonPressed' */
uint8 interfaces_interfaces_plusButtonPressed = false;
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MESSAGES
 ******************************************************************************/



/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/

/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



