#ifndef _ASD_INTERFACES_INTERFACES_AUTOMATIC_H_
#define _ASD_INTERFACES_INTERFACES_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    interfaces_interfaces_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    01.03.2019 10:47:06 Uhr
*
* @brief   "interfaces_interfaces>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"


/* component structure for module INTERFACES_INTERFACES_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ............interfaces_interfaces_Automatic */
#define _interfaces_interfaces_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by module interfaces_interfaces_Automatic
 ******************************************************************************/


/* declaration of messages */
extern float32 interfaces_interfaces_brake;
extern uint8 interfaces_interfaces_crash_detected;
extern uint8 interfaces_interfaces_plusButtonPressed;
extern float32 interfaces_interfaces_power;
extern float32 interfaces_interfaces_v;


#endif /* _ASD_INTERFACES_INTERFACES_AUTOMATIC_H_ */
