#ifndef _ASD_ACC_PC_AUTOMATIC_H_
#define _ASD_ACC_PC_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    ACC_PC_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    19.02.2019 16:15:37 Uhr
*
* @brief   "ACC_PC>>Automatic (project code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "chartab.h"
#include "components_AccFeedback_Automatic.h"
#include "components_Globals_Automatic.h"
#include "components_OnOff_Automatic.h"
#include "components_Stecke_Automatic.h"


/* component structure for project ACC_PC_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ...........................ACC_PC_Automatic */
#define _ACC_PC_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by project ACC_PC_Automatic
 ******************************************************************************/



#endif /* _ASD_ACC_PC_AUTOMATIC_H_ */
