/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Simulation_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 12:41:46 Uhr
*
* @brief   "components_Simulation>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Defines
 *----------------------------------------------------------------------------*/

#define __ASD_REQUIRES_OS_INFACE

/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_Simulation_Automatic.h"
#include "ACC_ECU_Automatic.h"
#include "components_Globals_Automatic.h"
#include "interfaces_interfaces_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_Simulation_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'components_Simulation'
 * data set:.....................................'COMPONENTS_SIMULATION_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const volatile struct components_Simulation_Automatic_CAL_MEM_SUBSTRUCT components_Simulation_CAL_MEM = {
   /* struct element:'components_Simulation_CAL_MEM.brakePadel' (modeled as:'brakePadel.components_Simulation') */
   0.0F,
   /* struct element:'components_Simulation_CAL_MEM.gasPadel' (modeled as:'gasPadel.components_Simulation') */
   0.0F,
   /* struct element:'components_Simulation_CAL_MEM.v_set' (modeled as:'v_set.components_Simulation') */
   0.0F,
   /* substruct: components_Simulation_CAL_MEM.ACC_Control_instance (modeled as:'ACC_Control_instance.components_Simulation') */
   {
      /* struct element:'components_Simulation_CAL_MEM.ACC_Control_instance.c_2' (modeled as:'c_2.ACC_Control_instance.components_Simulation') */
      0.0F,
      /* struct element:'components_Simulation_CAL_MEM.ACC_Control_instance.decrease_power' (modeled as:'decrease_power.ACC_Control_instance.components_Simulation') */
      5.0F,
      /* struct element:'components_Simulation_CAL_MEM.ACC_Control_instance.fuenf' (modeled as:'fuenf.ACC_Control_instance.components_Simulation') */
      5.0F,
      /* struct element:'components_Simulation_CAL_MEM.ACC_Control_instance.fuenfundneunzig' (modeled as:'fuenfundneunzig.ACC_Control_instance.components_Simulation') */
      95.0F,
      /* struct element:'components_Simulation_CAL_MEM.ACC_Control_instance.hundert' (modeled as:'hundert.ACC_Control_instance.components_Simulation') */
      100.0F,
      /* struct element:'components_Simulation_CAL_MEM.ACC_Control_instance.zero' (modeled as:'zero.ACC_Control_instance.components_Simulation') */
      0.0F
   },
   /* substruct: components_Simulation_CAL_MEM.AccFeedback_instance (modeled as:'AccFeedback_instance.components_Simulation') */
   {
      /* struct element:'components_Simulation_CAL_MEM.AccFeedback_instance.c' (modeled as:'c.AccFeedback_instance.components_Simulation') */
      0.0F
   },
   /* substruct: components_Simulation_CAL_MEM.Stecke_instance (modeled as:'Stecke_instance.components_Simulation') */
   {
      /* struct element:'components_Simulation_CAL_MEM.Stecke_instance.TrackSize' (modeled as:'TrackSize.Stecke_instance.components_Simulation') */
      1000.0F,
      /* struct element:'components_Simulation_CAL_MEM.Stecke_instance.AirFriction' (modeled as:'AirFriction.Stecke_instance.components_Simulation') */
      {
         6U,
         {
            0.0F, 30.0F, 60.0F, 90.0F, 120.0F, 150.0F
         },
         {
            0.0F, -0.1F, -0.2F, -0.4F, -0.8F, -1.6F
         }
      },
      /* struct element:'components_Simulation_CAL_MEM.Stecke_instance.BrakeMomentum' (modeled as:'BrakeMomentum.Stecke_instance.components_Simulation') */
      {
         6U,
         {
            0.0F, 1.0F, 40.0F, 60.0F, 80.0F, 100.0F
         },
         {
            0.0F, 0.0F, -1.0F, -2.0F, -3.0F, -4.0F
         }
      },
      /* struct element:'components_Simulation_CAL_MEM.Stecke_instance.EngineMomentum' (modeled as:'EngineMomentum.Stecke_instance.components_Simulation') */
      {
         6U,
         6U,
         {
            0.0F, 5.0F, 20.0F, 60.0F, 80.0F, 100.0F
         },
         {
            0.0F, 30.0F, 60.0F, 90.0F, 150.0F, 200.0F
         },
         {
            0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
            0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
            0.85F, 0.6F, 0.3F, 0.0F, 0.0F, 0.0F,
            3.15F, 2.35F, 1.55F, 0.8F, 0.4F, 0.0F,
            4.5F, 3.6F, 2.7F, 1.5F, 0.9F, 0.0F,
            5.0F, 4.5F, 3.8F, 2.8F, 1.9F, 0.0F
         }
      },
      /* struct element:'components_Simulation_CAL_MEM.Stecke_instance.Landscape' (modeled as:'Landscape.Stecke_instance.components_Simulation') */
      {
         20U,
         {
            0.0F, 100.0F, 145.5657F, 202.53F, 221.52F, 240.0F, 259.49F, 300.0F, 350.0F,
            400.0F, 450.0F, 500.0F, 600.0F, 700.0F, 750.0F, 800.0F, 810.0F, 850.0F, 900.0F,
            1000.0F
         },
         {
            0.0F, 4.0F, 7.125F, 10.375F, 10.75F, 10.5F, 9.0F, 5.375F, 2.625F, 0.625F, 1.25F,
            0.625F, 0.0F, 0.0F, 1.375F, 0.75F, 0.375F, 0.625F, 0.0F, 0.0F
         }
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_Simulation_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_Simulation_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'components_Simulation'
 * data set:.....................................'COMPONENTS_SIMULATION_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_Simulation_Automatic_RAM_SUBSTRUCT components_Simulation_RAM = {
   /* struct element:'components_Simulation_RAM.brakeVal' (modeled as:'brakeVal.components_Simulation') */
   0.0F,
   /* struct element:'components_Simulation_RAM.powerVal' (modeled as:'powerVal.components_Simulation') */
   0.0F,
   /* substruct: components_Simulation_RAM.ACC_Control_instance (modeled as:'ACC_Control_instance.components_Simulation') */
   {
      /* struct element:'components_Simulation_RAM.ACC_Control_instance.brake_return' (modeled as:'brake_return.ACC_Control_instance.components_Simulation') */
      0.0F,
      /* struct element:'components_Simulation_RAM.ACC_Control_instance.power_return' (modeled as:'power_return.ACC_Control_instance.components_Simulation') */
      0.0F,
      /* struct element:'components_Simulation_RAM.ACC_Control_instance.v_2' (modeled as:'v_2.ACC_Control_instance.components_Simulation') */
      0.0F,
      /* struct element:'components_Simulation_RAM.ACC_Control_instance.v_set' (modeled as:'v_set.ACC_Control_instance.components_Simulation') */
      0.0F
   },
   /* substruct: components_Simulation_RAM.AccFeedback_instance (modeled as:'AccFeedback_instance.components_Simulation') */
   {
      /* struct element:'components_Simulation_RAM.AccFeedback_instance.duration' (modeled as:'duration.AccFeedback_instance.components_Simulation') */
      0.0F,
      /* struct element:'components_Simulation_RAM.AccFeedback_instance.acc_status_old' (modeled as:'acc_status_old.AccFeedback_instance.components_Simulation') */
      false,
      /* struct element:'components_Simulation_RAM.AccFeedback_instance.feedback' (modeled as:'feedback.AccFeedback_instance.components_Simulation') */
      false
   },
   /* substruct: components_Simulation_RAM.Stecke_instance (modeled as:'Stecke_instance.components_Simulation') */
   {
      /* struct element:'components_Simulation_RAM.Stecke_instance.dh' (modeled as:'dh.Stecke_instance.components_Simulation') */
      0.0F,
      /* struct element:'components_Simulation_RAM.Stecke_instance.ds' (modeled as:'ds.Stecke_instance.components_Simulation') */
      0.0F,
      /* struct element:'components_Simulation_RAM.Stecke_instance.h' (modeled as:'h.Stecke_instance.components_Simulation') */
      0.0F,
      /* struct element:'components_Simulation_RAM.Stecke_instance.momentum' (modeled as:'momentum.Stecke_instance.components_Simulation') */
      0.0F,
      /* struct element:'components_Simulation_RAM.Stecke_instance.s' (modeled as:'s.Stecke_instance.components_Simulation') */
      0.0F
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_Simulation_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'components_Simulation'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_Simulation'
 * data set:.....................................'COMPONENTS_SIMULATION_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct components_Simulation_Automatic components_Simulation = {
   /* substruct: components_Simulation.ACC_Control_instance (modeled as:'ACC_Control_instance.components_Simulation') */
   {
      /* type descriptor pointer 'components_ACC_Control_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_Simulation_CAL_MEM.ACC_Control_instance,
      /* type descriptor pointer 'components_ACC_Control_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Simulation_RAM.ACC_Control_instance
   },
   /* substruct: components_Simulation.AccFeedback_instance (modeled as:'AccFeedback_instance.components_Simulation') */
   {
      /* type descriptor pointer 'components_AccFeedback_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_Simulation_CAL_MEM.AccFeedback_instance,
      /* type descriptor pointer 'components_AccFeedback_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Simulation_RAM.AccFeedback_instance
   },
   /* substruct: components_Simulation.Stecke_instance (modeled as:'Stecke_instance.components_Simulation') */
   {
      /* type descriptor pointer 'components_Stecke_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &components_Simulation_CAL_MEM.Stecke_instance,
      /* type descriptor pointer 'components_Stecke_Automatic_RAM' for memory class substruct for 'RAM' */
      &components_Simulation_RAM.Stecke_instance
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'components_Simulation'
 ******************************************************************************/





#define ACC_Control_instance_REF (&(components_Simulation.ACC_Control_instance))
#define AccFeedback_instance_REF (&(components_Simulation.AccFeedback_instance))
#define brakePadel_VAL (components_Simulation_CAL_MEM.brakePadel)
#define brakeVal_VAL (components_Simulation_RAM.brakeVal)
#define components_Globals_acc_status_request_VAL (components_Globals_acc_status_request)
#define components_Globals_v_VAL (components_Globals_v)
#define dT_VAL (ASD_DT_SCALED)
#define gasPadel_VAL (components_Simulation_CAL_MEM.gasPadel)
#define powerVal_VAL (components_Simulation_RAM.powerVal)
#define Stecke_instance_REF (&(components_Simulation.Stecke_instance))
#define v_set_VAL (components_Simulation_CAL_MEM.v_set)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'components_Simulation_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/
/* messages used by this process */


void components_Simulation_Automatic_calc (void)
{
   /* define local message copies */
   float32 interfaces_interfaces_v__components_Simulation_Automatic_calc;
   /* receive messages implicitly */
   {
      interfaces_interfaces_v__components_Simulation_Automatic_calc = interfaces_interfaces_v;
   }
   if (components_OnOff_Automatic_onoff(components_Stecke_Automatic_getV(Stecke_instance_REF), components_Globals_acc_status_request_VAL))
   {
      powerVal_VAL
         = components_ACC_Control_Automatic_getPower(ACC_Control_instance_REF);
      brakeVal_VAL
         = components_ACC_Control_Automatic_getBrake(ACC_Control_instance_REF);
   }
   else
   {
      brakeVal_VAL = brakePadel_VAL;
      powerVal_VAL = gasPadel_VAL;
   } /* end if */
   components_Stecke_Automatic_vCar(Stecke_instance_REF, brakeVal_VAL, powerVal_VAL, dT_VAL);
   interfaces_interfaces_v__components_Simulation_Automatic_calc = components_Stecke_Automatic_getV(Stecke_instance_REF);
   components_AccFeedback_Automatic_calc(AccFeedback_instance_REF, dT_VAL);
   components_ACC_Control_Automatic_calc(ACC_Control_instance_REF, components_Globals_v_VAL, powerVal_VAL, brakeVal_VAL, v_set_VAL);
   /* send messages implicitly */
   {
      interfaces_interfaces_v = interfaces_interfaces_v__components_Simulation_Automatic_calc;
   }
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'components_Simulation_Automatic_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



