#ifndef _ASD_COMPONENTS_DETECTCURRENTVELOCITY_AUTOMATIC_H_
#define _ASD_COMPONENTS_DETECTCURRENTVELOCITY_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_DetectCurrentVelocity_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 15:06:19 Uhr
*
* @brief   "components_DetectCurrentVelocity>>Automatic (module code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "chartab.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_DetectCurrentVelocity_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_DetectCurrentVelocity_Automatic_RAM_SUBSTRUCT {
   float32 v_buffer;
   uint8 acc_status_old;
   uint8 status_old;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_DetectCurrentVelocity_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'components_DetectCurrentVelocity_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct components_DetectCurrentVelocity_Automatic {
   struct components_DetectCurrentVelocity_Automatic_RAM_SUBSTRUCT * components_DetectCurrentVelocity_Automatic_RAM;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'components_DetectCurrentVelocity_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .components_DetectCurrentVelocity_Automatic */
#define _components_DetectCurrentVelocity_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class components_DetectCurrentVelocity_Automatic
 ******************************************************************************/
extern float32 components_DetectCurrentVelocity_Automatic_calc (
               const struct components_DetectCurrentVelocity_Automatic * self,
   /* IN    */ const uint8                                               status,
   /* IN    */ const float32                                             v
   );
extern float32 components_DetectCurrentVelocity_Automatic_getBuffer ( const struct components_DetectCurrentVelocity_Automatic * self);



#endif /* _ASD_COMPONENTS_DETECTCURRENTVELOCITY_AUTOMATIC_H_ */
