#ifndef _ASD_COMPONENTS_ONOFF_AUTOMATIC_H_
#define _ASD_COMPONENTS_ONOFF_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_OnOff_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    19.02.2019 16:15:37 Uhr
*
* @brief   "components_OnOff>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "chartab.h"


/* component structure for module COMPONENTS_ONOFF_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .................components_OnOff_Automatic */
#define _components_OnOff_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by module components_OnOff_Automatic
 ******************************************************************************/
extern void components_OnOff_Automatic_calc (void);



#endif /* _ASD_COMPONENTS_ONOFF_AUTOMATIC_H_ */
