/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_DetectCurrentVelocity_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 15:06:19 Uhr
*
* @brief   "components_DetectCurrentVelocity>>Automatic (module code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_DetectCurrentVelocity_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define status_old_VAL (self->components_DetectCurrentVelocity_Automatic_RAM->status_old)
#define v_buffer_VAL (self->components_DetectCurrentVelocity_Automatic_RAM->v_buffer)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_DetectCurrentVelocity_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_DetectCurrentVelocity_Automatic_calc (
               const struct components_DetectCurrentVelocity_Automatic * self,
   /* IN    */ const uint8                                               status,
   /* IN    */ const float32                                             v
   )
{
   if (status && (!status_old_VAL))
   {
      status_old_VAL = status;
      v_buffer_VAL = v;
   }
   else
   {
      status_old_VAL = status;
      return v_buffer_VAL;
   } /* end if */
   return v_buffer_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_DetectCurrentVelocity_Automatic_calc'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_DetectCurrentVelocity_Automatic_getBuffer'
 * ----------------------------------------------------------------------------
 * model name:...................................'getBuffer'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_DetectCurrentVelocity_Automatic_getBuffer ( const struct components_DetectCurrentVelocity_Automatic * self)
{
   return v_buffer_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_DetectCurrentVelocity_Automatic_getBuffer'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



