/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_AccFeedback_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    19.02.2019 16:15:37 Uhr
*
* @brief   "components_AccFeedback>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_AccFeedback_Automatic.h"
#include "ACC_PC_Automatic.h"
#include "components_Globals_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_AccFeedback_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'components_AccFeedback'
 * data set:.....................................'COMPONENTS_ACCFEEDBACK_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_AccFeedback_Automatic_CAL_MEM_SUBSTRUCT components_AccFeedback_CAL_MEM = {
   /* struct element:'components_AccFeedback_CAL_MEM.c' (modeled as:'c.components_AccFeedback') */
   0.0F
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_AccFeedback_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_AccFeedback_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'components_AccFeedback'
 * data set:.....................................'COMPONENTS_ACCFEEDBACK_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_AccFeedback_Automatic_RAM_SUBSTRUCT components_AccFeedback_RAM = {
   /* struct element:'components_AccFeedback_RAM.duration' (modeled as:'duration.components_AccFeedback') */
   0.0F,
   /* struct element:'components_AccFeedback_RAM.acc_status_old' (modeled as:'acc_status_old.components_AccFeedback') */
   false,
   /* struct element:'components_AccFeedback_RAM.feedback' (modeled as:'feedback.components_AccFeedback') */
   false
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_AccFeedback_RAM'
 ******************************************************************************/

/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_AccFeedback'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/





#define acc_status_old_VAL (components_AccFeedback_RAM.acc_status_old)
#define components_Globals_acc_feedback_VAL (components_Globals_acc_feedback)
#define components_Globals_acc_status_VAL (components_Globals_acc_status)
#define dT_VAL (ASD_DT_SCALED)
#define duration_VAL (components_AccFeedback_RAM.duration)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'components_AccFeedback_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_AccFeedback_Automatic_calc (void)
{
   if ((!components_Globals_acc_status_VAL) && (acc_status_old_VAL))
   {
      components_Globals_acc_feedback_VAL = true;
   } /* end if */
   acc_status_old_VAL = components_Globals_acc_status_VAL;
   if (components_Globals_acc_feedback_VAL)
   {
      duration_VAL = dT_VAL + duration_VAL;
   } /* end if */
   if (duration_VAL >= 3.0F)
   {
      components_Globals_acc_feedback_VAL = false;
      duration_VAL = 0.0F;
   } /* end if */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'components_AccFeedback_Automatic_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



