/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_ACC_Control_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 15:06:19 Uhr
*
* @brief   "components_ACC_Control>>Automatic (module code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_ACC_Control_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define brake_return_VAL (self->components_ACC_Control_Automatic_RAM->brake_return)
#define decrease_power_VAL (self->components_ACC_Control_Automatic_CAL_MEM->decrease_power)
#define fuenf_VAL (self->components_ACC_Control_Automatic_CAL_MEM->fuenf)
#define fuenfundneunzig_VAL (self->components_ACC_Control_Automatic_CAL_MEM->fuenfundneunzig)
#define hundert_VAL (self->components_ACC_Control_Automatic_CAL_MEM->hundert)
#define power_return_VAL (self->components_ACC_Control_Automatic_RAM->power_return)
#define zero_VAL (self->components_ACC_Control_Automatic_CAL_MEM->zero)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_ACC_Control_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_ACC_Control_Automatic_calc (
               const struct components_ACC_Control_Automatic * self,
   /* IN    */ const float32                                   v,
   /* IN    */ const float32                                   power,
   /* IN    */ const float32                                   brake,
   /* IN    */ const float32                                   esdl_calc_v_set
   )
{
   if (v > esdl_calc_v_set)
   {
      if (power > fuenf_VAL)
      {
         power_return_VAL = power - decrease_power_VAL;
      }
      else
      {
         power_return_VAL = zero_VAL;
         if (brake > fuenfundneunzig_VAL)
         {
            brake_return_VAL = hundert_VAL;
         }
         else
         {
            brake_return_VAL = brake + fuenf_VAL;
         } /* end if */
      } /* end if */
   }
   else
   {
      brake_return_VAL = zero_VAL;
      if (power > fuenfundneunzig_VAL)
      {
         power_return_VAL = hundert_VAL;
      }
      else
      {
         power_return_VAL = fuenf_VAL + power;
      } /* end if */
   } /* end if */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_ACC_Control_Automatic_calc'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_ACC_Control_Automatic_getBrake'
 * ----------------------------------------------------------------------------
 * model name:...................................'getBrake'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_ACC_Control_Automatic_getBrake ( const struct components_ACC_Control_Automatic * self)
{
   return brake_return_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_ACC_Control_Automatic_getBrake'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_ACC_Control_Automatic_getPower'
 * ----------------------------------------------------------------------------
 * model name:...................................'getPower'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_ACC_Control_Automatic_getPower ( const struct components_ACC_Control_Automatic * self)
{
   return power_return_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_ACC_Control_Automatic_getPower'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



