#ifndef _COMPONENTS_SIMULATION_AUTOMATIC_H_
#define _COMPONENTS_SIMULATION_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Simulation_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_Simulation
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define Stecke_instance_VAL components_Simulation.Stecke_instance
#define Stecke_instance_REF &(components_Simulation.Stecke_instance)
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_SIMULATION_AUTOMATIC_H_ */
