#ifndef _COMPONENTS_GLOBALS_AUTOMATIC_H_
#define _COMPONENTS_GLOBALS_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Globals_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_Globals
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define components_Globals_acc_status_VAL components_Globals_acc_status
#define components_Globals_acc_feedback_VAL components_Globals_acc_feedback
#define components_Globals_acc_status_request_VAL components_Globals_acc_status_request
#define components_Globals_v_VAL components_Globals_v
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_GLOBALS_AUTOMATIC_H_ */
