#ifndef _ASD_COMPONENTS_ACCFEEDBACK_AUTOMATIC_H_
#define _ASD_COMPONENTS_ACCFEEDBACK_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_AccFeedback_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    19.02.2019 16:15:37 Uhr
*
* @brief   "components_AccFeedback>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "chartab.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_AccFeedback_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct components_AccFeedback_Automatic_CAL_MEM_SUBSTRUCT {
   float32 c;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_AccFeedback_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_AccFeedback_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_AccFeedback_Automatic_RAM_SUBSTRUCT {
   float32 duration;
   uint8 acc_status_old;
   uint8 feedback;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_AccFeedback_Automatic'
 ******************************************************************************/


/* component structure for module COMPONENTS_ACCFEEDBACK_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ...........components_AccFeedback_Automatic */
#define _components_AccFeedback_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'components_AccFeedback_CAL_MEM' */
/* containing 'CAL_MEM' memory class tree */
extern struct components_AccFeedback_Automatic_CAL_MEM_SUBSTRUCT components_AccFeedback_CAL_MEM;

/* forward declaration of substruct variable 'components_AccFeedback_RAM' */
/* containing 'RAM' memory class tree */
extern struct components_AccFeedback_Automatic_RAM_SUBSTRUCT components_AccFeedback_RAM;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module components_AccFeedback_Automatic
 ******************************************************************************/
extern void components_AccFeedback_Automatic_calc (void);



#endif /* _ASD_COMPONENTS_ACCFEEDBACK_AUTOMATIC_H_ */
