/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Stecke_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    19.02.2019 16:15:37 Uhr
*
* @brief   "components_Stecke>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_Stecke_Automatic.h"
#include "ACC_PC_Automatic.h"
#include "components_Globals_Automatic.h"
#include "ESDL_Linear_Interpolation.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_Stecke_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'components_Stecke'
 * data set:.....................................'COMPONENTS_STECKE_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_Stecke_Automatic_CAL_MEM_SUBSTRUCT components_Stecke_CAL_MEM = {
   /* struct element:'components_Stecke_CAL_MEM.TrackSize' (modeled as:'TrackSize.components_Stecke') */
   1000.0F,
   /* struct element:'components_Stecke_CAL_MEM.AirFriction' (modeled as:'AirFriction.components_Stecke') */
   {
      6U,
      {
         0.0F, 30.0F, 60.0F, 90.0F, 120.0F, 150.0F
      },
      {
         0.0F, -0.1F, -0.2F, -0.4F, -0.8F, -1.6F
      }
   },
   /* struct element:'components_Stecke_CAL_MEM.BrakeMomentum' (modeled as:'BrakeMomentum.components_Stecke') */
   {
      6U,
      {
         0.0F, 1.0F, 40.0F, 60.0F, 80.0F, 100.0F
      },
      {
         0.0F, 0.0F, -1.0F, -2.0F, -3.0F, -4.0F
      }
   },
   /* struct element:'components_Stecke_CAL_MEM.EngineMomentum' (modeled as:'EngineMomentum.components_Stecke') */
   {
      6U,
      6U,
      {
         0.0F, 5.0F, 20.0F, 60.0F, 80.0F, 100.0F
      },
      {
         0.0F, 30.0F, 60.0F, 90.0F, 150.0F, 200.0F
      },
      {
         0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
         0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
         0.85F, 0.6F, 0.3F, 0.0F, 0.0F, 0.0F,
         3.15F, 2.35F, 1.55F, 0.8F, 0.4F, 0.0F,
         4.5F, 3.6F, 2.7F, 1.5F, 0.9F, 0.0F,
         5.0F, 4.5F, 3.8F, 2.8F, 1.9F, 0.0F
      }
   },
   /* struct element:'components_Stecke_CAL_MEM.Landscape' (modeled as:'Landscape.components_Stecke') */
   {
      20U,
      {
         0.0F, 100.0F, 145.5657F, 202.53F, 221.52F, 240.0F, 259.49F, 300.0F, 350.0F,
         400.0F, 450.0F, 500.0F, 600.0F, 700.0F, 750.0F, 800.0F, 810.0F, 850.0F, 900.0F,
         1000.0F
      },
      {
         0.0F, 4.0F, 7.125F, 10.375F, 10.75F, 10.5F, 9.0F, 5.375F, 2.625F, 0.625F, 1.25F,
         0.625F, 0.0F, 0.0F, 1.375F, 0.75F, 0.375F, 0.625F, 0.0F, 0.0F
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_Stecke_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_Stecke_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'components_Stecke'
 * data set:.....................................'COMPONENTS_STECKE_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_Stecke_Automatic_RAM_SUBSTRUCT components_Stecke_RAM = {
   /* struct element:'components_Stecke_RAM.dh' (modeled as:'dh.components_Stecke') */
   0.0F,
   /* struct element:'components_Stecke_RAM.ds' (modeled as:'ds.components_Stecke') */
   0.0F,
   /* struct element:'components_Stecke_RAM.h' (modeled as:'h.components_Stecke') */
   0.0F,
   /* struct element:'components_Stecke_RAM.momentum' (modeled as:'momentum.components_Stecke') */
   0.0F,
   /* struct element:'components_Stecke_RAM.s' (modeled as:'s.components_Stecke') */
   0.0F
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_Stecke_RAM'
 ******************************************************************************/

/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_Stecke'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/





#define AirFriction_REF (&(components_Stecke_CAL_MEM.AirFriction))
#define BrakeMomentum_REF (&(components_Stecke_CAL_MEM.BrakeMomentum))
#define components_Globals_v_VAL (components_Globals_v)
#define dh_VAL (components_Stecke_RAM.dh)
#define ds_VAL (components_Stecke_RAM.ds)
#define dT_VAL (ASD_DT_SCALED)
#define EngineMomentum_REF (&(components_Stecke_CAL_MEM.EngineMomentum))
#define h_VAL (components_Stecke_RAM.h)
#define Landscape_REF (&(components_Stecke_CAL_MEM.Landscape))
#define momentum_VAL (components_Stecke_RAM.momentum)
#define s_VAL (components_Stecke_RAM.s)
#define TrackSize_VAL (components_Stecke_CAL_MEM.TrackSize)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF PROCESS 'components_Stecke_Automatic_strecke_test'
 * ----------------------------------------------------------------------------
 * model name:...................................'strecke_test'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_Stecke_Automatic_strecke_test (void)
{
   components_Stecke_Automatic_vCar(0.0F, 20.0F);
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF PROCESS 'components_Stecke_Automatic_strecke_test'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Stecke_Automatic_vCar'
 * ----------------------------------------------------------------------------
 * model name:...................................'vCar'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_Stecke_Automatic_vCar (
   /* IN    */ const float32 brakeCtrl,
   /* IN    */ const float32 powerCtrl
   )
{
   if (s_VAL > TrackSize_VAL)
   {
      s_VAL = 0.0F;
   } /* end if */
   momentum_VAL
      = ESDL_Linear_CharTable2_getAt_r32r32r32((EngineMomentum_REF)->xSize, (EngineMomentum_REF)->xDist, (EngineMomentum_REF)->ySize, (EngineMomentum_REF)->yDist, (EngineMomentum_REF)->values, powerCtrl, components_Globals_v_VAL);
   ds_VAL = (components_Globals_v_VAL * dT_VAL) / 3.6F;
   s_VAL = ds_VAL + s_VAL;
   dh_VAL
      = h_VAL - ESDL_Linear_CharTable1_getAt_r32r32((Landscape_REF)->xSize, (Landscape_REF)->xDist, (Landscape_REF)->values, s_VAL);
   h_VAL
      = ESDL_Linear_CharTable1_getAt_r32r32((Landscape_REF)->xSize, (Landscape_REF)->xDist, (Landscape_REF)->values, s_VAL);
   components_Globals_v_VAL
      = ((ESDL_Linear_CharTable1_getAt_r32r32((BrakeMomentum_REF)->xSize, (BrakeMomentum_REF)->xDist, (BrakeMomentum_REF)->values, brakeCtrl) + momentum_VAL + ESDL_Linear_CharTable1_getAt_r32r32((AirFriction_REF)->xSize, (AirFriction_REF)->xDist, (AirFriction_REF)->values, components_Globals_v_VAL) + ((((ds_VAL == 0.0F) ? dh_VAL : (dh_VAL / ds_VAL))) * 9.81F)) * dT_VAL * 3.6F) + components_Globals_v_VAL;
   if (components_Globals_v_VAL < 0.0F)
   {
      components_Globals_v_VAL = 0.0F;
   } /* end if */
   return components_Globals_v_VAL;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Stecke_Automatic_vCar'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



