/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_AccFeedback_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 12:41:46 Uhr
*
* @brief   "components_AccFeedback>>Automatic (module code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_AccFeedback_Automatic.h"
#include "components_Globals_Automatic.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



#define acc_status_old_VAL (self->components_AccFeedback_Automatic_RAM->acc_status_old)
#define components_Globals_acc_feedback_VAL (components_Globals_acc_feedback)
#define components_Globals_acc_status_VAL (components_Globals_acc_status)
#define duration_VAL (self->components_AccFeedback_Automatic_RAM->duration)


/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_AccFeedback_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_AccFeedback_Automatic_calc (
               const struct components_AccFeedback_Automatic * self,
   /* IN    */ const float32                                   my_dT
   )
{
   if ((!components_Globals_acc_status_VAL) && (acc_status_old_VAL))
   {
      components_Globals_acc_feedback_VAL = true;
   } /* end if */
   acc_status_old_VAL = components_Globals_acc_status_VAL;
   if (components_Globals_acc_feedback_VAL)
   {
      duration_VAL = my_dT + duration_VAL;
   } /* end if */
   if (duration_VAL >= 3.0F)
   {
      components_Globals_acc_feedback_VAL = false;
      duration_VAL = 0.0F;
   } /* end if */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_AccFeedback_Automatic_calc'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



