#ifndef _ASD_COMPONENTS_ACC_CONTROL_AUTOMATIC_H_
#define _ASD_COMPONENTS_ACC_CONTROL_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_ACC_Control_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 15:06:19 Uhr
*
* @brief   "components_ACC_Control>>Automatic (module code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "chartab.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_ACC_Control_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct components_ACC_Control_Automatic_CAL_MEM_SUBSTRUCT {
   float32 c_2;
   float32 decrease_power;
   float32 fuenf;
   float32 fuenfundneunzig;
   float32 hundert;
   float32 zero;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_ACC_Control_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_ACC_Control_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_ACC_Control_Automatic_RAM_SUBSTRUCT {
   float32 brake_return;
   float32 power_return;
   float32 v_2;
   float32 v_set;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR CLASS 'components_ACC_Control_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR CLASS 'components_ACC_Control_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct components_ACC_Control_Automatic {
   struct components_ACC_Control_Automatic_CAL_MEM_SUBSTRUCT * components_ACC_Control_Automatic_CAL_MEM;
   struct components_ACC_Control_Automatic_RAM_SUBSTRUCT * components_ACC_Control_Automatic_RAM;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR CLASS 'components_ACC_Control_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ...........components_ACC_Control_Automatic */
#define _components_ACC_Control_Automatic_TYPE_DEF_




/******************************************************************************
 * BEGIN: declaration of global C functions defined by class components_ACC_Control_Automatic
 ******************************************************************************/
extern void components_ACC_Control_Automatic_calc (
               const struct components_ACC_Control_Automatic * self,
   /* IN    */ const float32                                   v,
   /* IN    */ const float32                                   power,
   /* IN    */ const float32                                   brake,
   /* IN    */ const float32                                   esdl_calc_v_set
   );
extern float32 components_ACC_Control_Automatic_getBrake ( const struct components_ACC_Control_Automatic * self);
extern float32 components_ACC_Control_Automatic_getPower ( const struct components_ACC_Control_Automatic * self);



#endif /* _ASD_COMPONENTS_ACC_CONTROL_AUTOMATIC_H_ */
