#ifndef _COMPONENTS_STECKE_AUTOMATIC_H_
#define _COMPONENTS_STECKE_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Stecke_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_Stecke
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define h_VAL components_Stecke_RAM.h
#define s_VAL components_Stecke_RAM.s
#define ds_VAL components_Stecke_RAM.ds
#define momentum_VAL components_Stecke_RAM.momentum
#define BrakeMomentum_VAL components_Stecke_CAL_MEM.BrakeMomentum
#define BrakeMomentum_REF &(components_Stecke_CAL_MEM.BrakeMomentum)
#define EngineMomentum_VAL components_Stecke_CAL_MEM.EngineMomentum
#define EngineMomentum_REF &(components_Stecke_CAL_MEM.EngineMomentum)
#define AirFriction_VAL components_Stecke_CAL_MEM.AirFriction
#define AirFriction_REF &(components_Stecke_CAL_MEM.AirFriction)
#define dh_VAL components_Stecke_RAM.dh
#define Landscape_VAL components_Stecke_CAL_MEM.Landscape
#define Landscape_REF &(components_Stecke_CAL_MEM.Landscape)
#define TrackSize_VAL components_Stecke_CAL_MEM.TrackSize
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_STECKE_AUTOMATIC_H_ */
