#ifndef _COMPONENTS_SIMULATION_AUTOMATIC_H_
#define _COMPONENTS_SIMULATION_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Simulation_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_Simulation
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define Stecke_instance_VAL components_Simulation.Stecke_instance
#define Stecke_instance_REF &(components_Simulation.Stecke_instance)
#define OnOff_instance_VAL OnOff_instance_components_Simulation
#define OnOff_instance_REF &(OnOff_instance_components_Simulation)
#define brakePadel_VAL components_Simulation_CAL_MEM.brakePadel
#define gasPadel_VAL components_Simulation_CAL_MEM.gasPadel
#define brakeVal_VAL components_Simulation_RAM.brakeVal
#define powerVal_VAL components_Simulation_RAM.powerVal
#define AccFeedback_instance_VAL components_Simulation.AccFeedback_instance
#define AccFeedback_instance_REF &(components_Simulation.AccFeedback_instance)
#define ACC_Control_instance_VAL components_Simulation.ACC_Control_instance
#define ACC_Control_instance_REF &(components_Simulation.ACC_Control_instance)
#define DetectCurrentVelocity_instance_VAL components_Simulation.DetectCurrentVelocity_instance
#define DetectCurrentVelocity_instance_REF &(components_Simulation.DetectCurrentVelocity_instance)
#define FuSi_instance_VAL FuSi_instance_components_Simulation
#define FuSi_instance_REF &(FuSi_instance_components_Simulation)
#define crash_VAL components_Simulation_CAL_MEM.crash
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_SIMULATION_AUTOMATIC_H_ */
