#ifndef _COMPONENTS_DETECTCURRENTVELOCITY_AUTOMATIC_H_
#define _COMPONENTS_DETECTCURRENTVELOCITY_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_DetectCurrentVelocity_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_DetectCurrentVelocity
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define acc_status_old_VAL self->components_DetectCurrentVelocity_Automatic_RAM->acc_status_old
#define status_old_VAL self->components_DetectCurrentVelocity_Automatic_RAM->status_old
#define v_buffer_VAL self->components_DetectCurrentVelocity_Automatic_RAM->v_buffer
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_DETECTCURRENTVELOCITY_AUTOMATIC_H_ */
