#ifndef _COMPONENTS_ACCFEEDBACK_AUTOMATIC_H_
#define _COMPONENTS_ACCFEEDBACK_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_AccFeedback_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_AccFeedback
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define c_VAL self->components_AccFeedback_Automatic_CAL_MEM->c
#define acc_status_old_VAL self->components_AccFeedback_Automatic_RAM->acc_status_old
#define feedback_VAL self->components_AccFeedback_Automatic_RAM->feedback
#define duration_VAL self->components_AccFeedback_Automatic_RAM->duration
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_ACCFEEDBACK_AUTOMATIC_H_ */
