#ifndef _COMPONENTS_ACC_CONTROL_AUTOMATIC_H_
#define _COMPONENTS_ACC_CONTROL_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_ACC_Control_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_ACC_Control
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define v_set_VAL self->components_ACC_Control_Automatic_RAM->v_set
#define fuenf_VAL self->components_ACC_Control_Automatic_CAL_MEM->fuenf
#define v_2_VAL self->components_ACC_Control_Automatic_RAM->v_2
#define decrease_power_VAL self->components_ACC_Control_Automatic_CAL_MEM->decrease_power
#define power_return_VAL self->components_ACC_Control_Automatic_RAM->power_return
#define zero_VAL self->components_ACC_Control_Automatic_CAL_MEM->zero
#define brake_return_VAL self->components_ACC_Control_Automatic_RAM->brake_return
#define c_2_VAL self->components_ACC_Control_Automatic_CAL_MEM->c_2
#define fuenfundneunzig_VAL self->components_ACC_Control_Automatic_CAL_MEM->fuenfundneunzig
#define hundert_VAL self->components_ACC_Control_Automatic_CAL_MEM->hundert
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_ACC_CONTROL_AUTOMATIC_H_ */
