#ifndef _COMPONENTS_STECKE_AUTOMATIC_H_
#define _COMPONENTS_STECKE_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Stecke_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component components_Stecke
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define h_VAL self->components_Stecke_Automatic_RAM->h
#define s_VAL self->components_Stecke_Automatic_RAM->s
#define ds_VAL self->components_Stecke_Automatic_RAM->ds
#define momentum_VAL self->components_Stecke_Automatic_RAM->momentum
#define BrakeMomentum_VAL self->components_Stecke_Automatic_CAL_MEM->BrakeMomentum
#define BrakeMomentum_REF &(self->components_Stecke_Automatic_CAL_MEM->BrakeMomentum)
#define EngineMomentum_VAL self->components_Stecke_Automatic_CAL_MEM->EngineMomentum
#define EngineMomentum_REF &(self->components_Stecke_Automatic_CAL_MEM->EngineMomentum)
#define AirFriction_VAL self->components_Stecke_Automatic_CAL_MEM->AirFriction
#define AirFriction_REF &(self->components_Stecke_Automatic_CAL_MEM->AirFriction)
#define dh_VAL self->components_Stecke_Automatic_RAM->dh
#define Landscape_VAL self->components_Stecke_Automatic_CAL_MEM->Landscape
#define Landscape_REF &(self->components_Stecke_Automatic_CAL_MEM->Landscape)
#define TrackSize_VAL self->components_Stecke_Automatic_RAM->TrackSize
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _COMPONENTS_STECKE_AUTOMATIC_H_ */
