#ifndef ESDL_MESSAGECOPY_H
#define ESDL_MESSAGECOPY_H

/**
  * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  * 
  * @file    esdl_messageCopy.h
  * 
  * @author  Generated by ASCET-DEVELOPER V7.4.0
  * 
  * @date    3/5/2019 12:41:46 PM
  * 
  * @brief   Header file for message copy logic
  **/



#endif /* ESDL_MESSAGECOPY_H */
