#ifndef _INTERFACES_INTERFACES_AUTOMATIC_H_
#define _INTERFACES_INTERFACES_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    interfaces_interfaces_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0
*
* @brief   contains access macro definitions to the elements of component interfaces_interfaces
*
*/
/******************************************************************************
 * BEGIN: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#define interfaces_interfaces_crash_detected_VAL interfaces_interfaces_crash_detected
#define interfaces_interfaces_plusButtonPressed_VAL interfaces_interfaces_plusButtonPressed
#define interfaces_interfaces_brake_VAL interfaces_interfaces_brake
#define interfaces_interfaces_power_VAL interfaces_interfaces_power
#define interfaces_interfaces_v_VAL interfaces_interfaces_v
/* ****************************************************************************
 * END: DEFINITION OF ACCESS MACROS
 ******************************************************************************/
#endif /* _INTERFACES_INTERFACES_AUTOMATIC_H_ */
