/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_Simulation_Automatic.l1.c
 *
 * @author  Generated by ASCET
 *
 * @brief   Definitions for L1 node: components_Simulation_Automatic
 *
 **/
#include "components_Simulation_Automatic.l1.h"
#include "components_Simulation_Automatic_private.h"

/**
 * Class initialization 
 **/
void initClass_L1_components_Simulation_Automatic (L1_components_Simulation_Automatic_Class* _ASCET_class)
{
}


static MethodList _ObjectMethodList = {
    ((void *)0)
};

static MethodList _ClassMethodList = {
    ((void *)0)
};

/**
 * Global objects 
 **/
struct L1_components_Simulation_Automatic_Obj* L1_components_Simulation_AutomaticInstance = NULL;

static ASDClassHeader L1_components_Simulation_Automatic_ClassHeader = {
	0, 0, 9, 0, &_ObjectMethodList, &_ClassMethodList
};

L1_components_Simulation_Automatic_Class L1_components_Simulation_Automatic_ClassObj = {{1, {&L1_components_Simulation_Automatic_ClassHeader}, {0}}};

bool initialized_components_Simulation_Automatic = false;

/**
 * Initialize this L1 component 
 **/
struct L1_components_Simulation_Automatic_Obj* initInstance_L1_components_Simulation_Automatic(void)
{
    struct L1_components_Simulation_Automatic_Obj* L1_Instance = NULL;
    if (!initialized_components_Simulation_Automatic) {
        /* for first time also static class data shall be initialized */
        initialized_components_Simulation_Automatic = true;
        initClass_L1_components_Simulation_Automatic(&L1_components_Simulation_Automatic_ClassObj);
    }

    /* create L1 object and initialize it */
    CREATE_OBJECT (L1_Instance, L1_components_Simulation_Automatic);
    L1_Instance->Stecke_instance = initInstance_L1_components_Stecke_Automatic(&Stecke_instance_VAL);
    L1_Instance->AccFeedback_instance = initInstance_L1_components_AccFeedback_Automatic(&AccFeedback_instance_VAL);
    L1_Instance->ACC_Control_instance = initInstance_L1_components_ACC_Control_Automatic(&ACC_Control_instance_VAL);
    L1_Instance->DetectCurrentVelocity_instance = initInstance_L1_components_DetectCurrentVelocity_Automatic(&DetectCurrentVelocity_instance_VAL);
    L1_Instance->brakePadel = initInstance_scalarWrapper((uint32)&brakePadel_VAL, sizeof(float32), ASD_PARAMETER);
    L1_Instance->gasPadel = initInstance_scalarWrapper((uint32)&gasPadel_VAL, sizeof(float32), ASD_PARAMETER);
    L1_Instance->brakeVal = initInstance_scalarWrapper((uint32)&brakeVal_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->powerVal = initInstance_scalarWrapper((uint32)&powerVal_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->crash = initInstance_scalarWrapper((uint32)&crash_VAL, sizeof(uint8), ASD_PARAMETER);
    L1_components_Simulation_AutomaticInstance = L1_Instance;

    return L1_Instance;
}
