#ifndef _STRUCTURE_ASD_L1_components_Simulation_Automatic
#define _STRUCTURE_ASD_L1_components_Simulation_Automatic
/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_Simulation_Automatic.l1.h
 *
 * @author  Generated by ASCET
 *
 * @brief   Declarations for L1 node: components_Simulation_Automatic
 *
 **/
#include "a_basdef.h"
#include "components_Simulation_Automatic.h"
#include "components_Stecke_Automatic.l1.h"
#include "components_AccFeedback_Automatic.l1.h"
#include "components_ACC_Control_Automatic.l1.h"
#include "components_DetectCurrentVelocity_Automatic.l1.h"

/**
 * local variables object structure 
 **/
struct L1_components_Simulation_Automatic_Obj {
	ASDObjectHeader objectHeader;
	struct L1_components_Stecke_Automatic_Obj* Stecke_instance;
	struct L1_components_AccFeedback_Automatic_Obj* AccFeedback_instance;
	struct L1_components_ACC_Control_Automatic_Obj* ACC_Control_instance;
	struct L1_components_DetectCurrentVelocity_Automatic_Obj* DetectCurrentVelocity_instance;
	scalarWrapper_Obj* brakePadel;
	scalarWrapper_Obj* gasPadel;
	scalarWrapper_Obj* brakeVal;
	scalarWrapper_Obj* powerVal;
	scalarWrapper_Obj* crash;
};

/**
 * static variables object structure 
 **/
typedef struct {
	ASDObjectHeader objectHeader;
} L1_components_Simulation_Automatic_Class;

extern L1_components_Simulation_Automatic_Class L1_components_Simulation_Automatic_ClassObj;

/**
 * external functions 
 **/
extern void initClass_L1_components_Simulation_Automatic (L1_components_Simulation_Automatic_Class* _ASCET_class);
extern struct L1_components_Simulation_Automatic_Obj* initInstance_L1_components_Simulation_Automatic(void);
#endif /* _STRUCTURE_ASD_L1_components_Simulation_Automatic */
