/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_DetectCurrentVelocity_Automatic.l1.c
 *
 * @author  Generated by ASCET
 *
 * @brief   Definitions for L1 node: components_DetectCurrentVelocity_Automatic
 *
 **/
#include "components_DetectCurrentVelocity_Automatic.l1.h"
#include "components_DetectCurrentVelocity_Automatic_private.h"

/**
 * Class initialization 
 **/
void initClass_L1_components_DetectCurrentVelocity_Automatic (L1_components_DetectCurrentVelocity_Automatic_Class* _ASCET_class)
{
}


static MethodList _ObjectMethodList = {
    ((void *)0)
};

static MethodList _ClassMethodList = {
    ((void *)0)
};

/**
 * Global objects 
 **/
static ASDClassHeader L1_components_DetectCurrentVelocity_Automatic_ClassHeader = {
	0, 0, 3, 0, &_ObjectMethodList, &_ClassMethodList
};

L1_components_DetectCurrentVelocity_Automatic_Class L1_components_DetectCurrentVelocity_Automatic_ClassObj = {{1, {&L1_components_DetectCurrentVelocity_Automatic_ClassHeader}, {0}}};

bool initialized_components_DetectCurrentVelocity_Automatic = false;

/**
 * Initialize this L1 component 
 **/
struct L1_components_DetectCurrentVelocity_Automatic_Obj* initInstance_L1_components_DetectCurrentVelocity_Automatic(const struct components_DetectCurrentVelocity_Automatic* self)
{
    struct L1_components_DetectCurrentVelocity_Automatic_Obj* L1_Instance = NULL;
    if (!initialized_components_DetectCurrentVelocity_Automatic) {
        /* for first time also static class data shall be initialized */
        initialized_components_DetectCurrentVelocity_Automatic = true;
        initClass_L1_components_DetectCurrentVelocity_Automatic(&L1_components_DetectCurrentVelocity_Automatic_ClassObj);
    }

    /* create L1 object and initialize it */
    CREATE_OBJECT (L1_Instance, L1_components_DetectCurrentVelocity_Automatic);
    L1_Instance->acc_status_old = initInstance_scalarWrapper((uint32)&acc_status_old_VAL, sizeof(uint8), ASD_VARIABLE);
    L1_Instance->status_old = initInstance_scalarWrapper((uint32)&status_old_VAL, sizeof(uint8), ASD_VARIABLE);
    L1_Instance->v_buffer = initInstance_scalarWrapper((uint32)&v_buffer_VAL, sizeof(float32), ASD_VARIABLE);

    return L1_Instance;
}
