/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_AccFeedback_Automatic.l1.c
 *
 * @author  Generated by ASCET
 *
 * @brief   Definitions for L1 node: components_AccFeedback_Automatic
 *
 **/
#include "components_AccFeedback_Automatic.l1.h"
#include "components_AccFeedback_Automatic_private.h"

/**
 * Class initialization 
 **/
void initClass_L1_components_AccFeedback_Automatic (L1_components_AccFeedback_Automatic_Class* _ASCET_class)
{
}


static MethodList _ObjectMethodList = {
    ((void *)0)
};

static MethodList _ClassMethodList = {
    ((void *)0)
};

/**
 * Global objects 
 **/
struct L1_components_AccFeedback_Automatic_Obj* L1_components_AccFeedback_AutomaticInstance = NULL;

static ASDClassHeader L1_components_AccFeedback_Automatic_ClassHeader = {
	0, 0, 4, 0, &_ObjectMethodList, &_ClassMethodList
};

L1_components_AccFeedback_Automatic_Class L1_components_AccFeedback_Automatic_ClassObj = {{1, {&L1_components_AccFeedback_Automatic_ClassHeader}, {0}}};

bool initialized_components_AccFeedback_Automatic = false;

/**
 * Initialize this L1 component 
 **/
struct L1_components_AccFeedback_Automatic_Obj* initInstance_L1_components_AccFeedback_Automatic(void)
{
    struct L1_components_AccFeedback_Automatic_Obj* L1_Instance = NULL;
    if (!initialized_components_AccFeedback_Automatic) {
        /* for first time also static class data shall be initialized */
        initialized_components_AccFeedback_Automatic = true;
        initClass_L1_components_AccFeedback_Automatic(&L1_components_AccFeedback_Automatic_ClassObj);
    }

    /* create L1 object and initialize it */
    CREATE_OBJECT (L1_Instance, L1_components_AccFeedback_Automatic);
    L1_Instance->c = initInstance_scalarWrapper((uint32)&c_VAL, sizeof(float32), ASD_PARAMETER);
    L1_Instance->acc_status_old = initInstance_scalarWrapper((uint32)&acc_status_old_VAL, sizeof(uint8), ASD_VARIABLE);
    L1_Instance->feedback = initInstance_scalarWrapper((uint32)&feedback_VAL, sizeof(uint8), ASD_VARIABLE);
    L1_Instance->duration = initInstance_scalarWrapper((uint32)&duration_VAL, sizeof(float32), ASD_VARIABLE);
    L1_components_AccFeedback_AutomaticInstance = L1_Instance;

    return L1_Instance;
}
