/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_ACC_Control_Automatic.l1.c
 *
 * @author  Generated by ASCET
 *
 * @brief   Definitions for L1 node: components_ACC_Control_Automatic
 *
 **/
#include "components_ACC_Control_Automatic.l1.h"
#include "components_ACC_Control_Automatic_private.h"

/**
 * Class initialization 
 **/
void initClass_L1_components_ACC_Control_Automatic (L1_components_ACC_Control_Automatic_Class* _ASCET_class)
{
}


static MethodList _ObjectMethodList = {
    ((void *)0)
};

static MethodList _ClassMethodList = {
    ((void *)0)
};

/**
 * Global objects 
 **/
static ASDClassHeader L1_components_ACC_Control_Automatic_ClassHeader = {
	0, 0, 10, 0, &_ObjectMethodList, &_ClassMethodList
};

L1_components_ACC_Control_Automatic_Class L1_components_ACC_Control_Automatic_ClassObj = {{1, {&L1_components_ACC_Control_Automatic_ClassHeader}, {0}}};

bool initialized_components_ACC_Control_Automatic = false;

/**
 * Initialize this L1 component 
 **/
struct L1_components_ACC_Control_Automatic_Obj* initInstance_L1_components_ACC_Control_Automatic(const struct components_ACC_Control_Automatic* self)
{
    struct L1_components_ACC_Control_Automatic_Obj* L1_Instance = NULL;
    if (!initialized_components_ACC_Control_Automatic) {
        /* for first time also static class data shall be initialized */
        initialized_components_ACC_Control_Automatic = true;
        initClass_L1_components_ACC_Control_Automatic(&L1_components_ACC_Control_Automatic_ClassObj);
    }

    /* create L1 object and initialize it */
    CREATE_OBJECT (L1_Instance, L1_components_ACC_Control_Automatic);
    L1_Instance->v_set = initInstance_scalarWrapper((uint32)&v_set_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->fuenf = initInstance_scalarWrapper((uint32)&fuenf_VAL, sizeof(float32), ASD_PARAMETER);
    L1_Instance->v_2 = initInstance_scalarWrapper((uint32)&v_2_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->decrease_power = initInstance_scalarWrapper((uint32)&decrease_power_VAL, sizeof(float32), ASD_PARAMETER);
    L1_Instance->power_return = initInstance_scalarWrapper((uint32)&power_return_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->zero = initInstance_scalarWrapper((uint32)&zero_VAL, sizeof(float32), ASD_PARAMETER);
    L1_Instance->brake_return = initInstance_scalarWrapper((uint32)&brake_return_VAL, sizeof(float32), ASD_VARIABLE);
    L1_Instance->c_2 = initInstance_scalarWrapper((uint32)&c_2_VAL, sizeof(float32), ASD_PARAMETER);
    L1_Instance->fuenfundneunzig = initInstance_scalarWrapper((uint32)&fuenfundneunzig_VAL, sizeof(float32), ASD_PARAMETER);
    L1_Instance->hundert = initInstance_scalarWrapper((uint32)&hundert_VAL, sizeof(float32), ASD_PARAMETER);

    return L1_Instance;
}
