#ifndef _STRUCTURE_ASD_L1_components_AccFeedback_Automatic
#define _STRUCTURE_ASD_L1_components_AccFeedback_Automatic
/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_AccFeedback_Automatic.l1.h
 *
 * @author  Generated by ASCET
 *
 * @brief   Declarations for L1 node: components_AccFeedback_Automatic
 *
 **/
#include "a_basdef.h"
#include "components_AccFeedback_Automatic.h"

/**
 * local variables object structure 
 **/
struct L1_components_AccFeedback_Automatic_Obj {
	ASDObjectHeader objectHeader;
	scalarWrapper_Obj* c;
	scalarWrapper_Obj* acc_status_old;
	scalarWrapper_Obj* feedback;
	scalarWrapper_Obj* duration;
};

/**
 * static variables object structure 
 **/
typedef struct {
	ASDObjectHeader objectHeader;
} L1_components_AccFeedback_Automatic_Class;

extern L1_components_AccFeedback_Automatic_Class L1_components_AccFeedback_Automatic_ClassObj;

/**
 * external functions 
 **/
extern void initClass_L1_components_AccFeedback_Automatic (L1_components_AccFeedback_Automatic_Class* _ASCET_class);
extern struct L1_components_AccFeedback_Automatic_Obj* initInstance_L1_components_AccFeedback_Automatic(const struct components_AccFeedback_Automatic* self);
#endif /* _STRUCTURE_ASD_L1_components_AccFeedback_Automatic */
