#ifndef _STRUCTURE_ASD_L1_components_ACC_Control_Automatic
#define _STRUCTURE_ASD_L1_components_ACC_Control_Automatic
/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    components_ACC_Control_Automatic.l1.h
 *
 * @author  Generated by ASCET
 *
 * @brief   Declarations for L1 node: components_ACC_Control_Automatic
 *
 **/
#include "a_basdef.h"
#include "components_ACC_Control_Automatic.h"

/**
 * local variables object structure 
 **/
struct L1_components_ACC_Control_Automatic_Obj {
	ASDObjectHeader objectHeader;
	scalarWrapper_Obj* v_set;
	scalarWrapper_Obj* fuenf;
	scalarWrapper_Obj* v_2;
	scalarWrapper_Obj* decrease_power;
	scalarWrapper_Obj* power_return;
	scalarWrapper_Obj* zero;
	scalarWrapper_Obj* brake_return;
	scalarWrapper_Obj* c_2;
	scalarWrapper_Obj* fuenfundneunzig;
	scalarWrapper_Obj* hundert;
};

/**
 * static variables object structure 
 **/
typedef struct {
	ASDObjectHeader objectHeader;
} L1_components_ACC_Control_Automatic_Class;

extern L1_components_ACC_Control_Automatic_Class L1_components_ACC_Control_Automatic_ClassObj;

/**
 * external functions 
 **/
extern void initClass_L1_components_ACC_Control_Automatic (L1_components_ACC_Control_Automatic_Class* _ASCET_class);
extern struct L1_components_ACC_Control_Automatic_Obj* initInstance_L1_components_ACC_Control_Automatic(const struct components_ACC_Control_Automatic* self);
#endif /* _STRUCTURE_ASD_L1_components_ACC_Control_Automatic */
