/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    interfaces_interfaces_Automatic.l1.c
 *
 * @author  Generated by ASCET
 *
 * @brief   Definitions for L1 node: interfaces_interfaces_Automatic
 *
 **/
#include "interfaces_interfaces_Automatic.l1.h"
#include "interfaces_interfaces_Automatic_private.h"

/**
 * Class initialization 
 **/
void initClass_L1_interfaces_interfaces_Automatic (L1_interfaces_interfaces_Automatic_Class* _ASCET_class)
{
    _ASCET_class->crash_detected = initInstance_scalarWrapper((uint32)&interfaces_interfaces_crash_detected_VAL, sizeof(uint8), ASD_VARIABLE);
    _ASCET_class->plusButtonPressed = initInstance_scalarWrapper((uint32)&interfaces_interfaces_plusButtonPressed_VAL, sizeof(uint8), ASD_VARIABLE);
    _ASCET_class->brake = initInstance_scalarWrapper((uint32)&interfaces_interfaces_brake_VAL, sizeof(float32), ASD_VARIABLE);
    _ASCET_class->power = initInstance_scalarWrapper((uint32)&interfaces_interfaces_power_VAL, sizeof(float32), ASD_VARIABLE);
    _ASCET_class->v = initInstance_scalarWrapper((uint32)&interfaces_interfaces_v_VAL, sizeof(float32), ASD_VARIABLE);
}


static MethodList _ObjectMethodList = {
    ((void *)0)
};

static MethodList _ClassMethodList = {
    ((void *)0)
};

/**
 * Global objects 
 **/
struct L1_interfaces_interfaces_Automatic_Obj* L1_interfaces_interfaces_AutomaticInstance = NULL;

static ASDClassHeader L1_interfaces_interfaces_Automatic_ClassHeader = {
	0, 0, 0, 5, &_ObjectMethodList, &_ClassMethodList
};

L1_interfaces_interfaces_Automatic_Class L1_interfaces_interfaces_Automatic_ClassObj = {{1, {&L1_interfaces_interfaces_Automatic_ClassHeader}, {0}}};

bool initialized_interfaces_interfaces_Automatic = false;

/**
 * Initialize this L1 component 
 **/
struct L1_interfaces_interfaces_Automatic_Obj* initInstance_L1_interfaces_interfaces_Automatic(void)
{
    struct L1_interfaces_interfaces_Automatic_Obj* L1_Instance = NULL;
    if (!initialized_interfaces_interfaces_Automatic) {
        /* for first time also static class data shall be initialized */
        initialized_interfaces_interfaces_Automatic = true;
        initClass_L1_interfaces_interfaces_Automatic(&L1_interfaces_interfaces_Automatic_ClassObj);
    }

    /* create L1 object and initialize it */
    CREATE_OBJECT (L1_Instance, L1_interfaces_interfaces_Automatic);
    L1_interfaces_interfaces_AutomaticInstance = L1_Instance;

    return L1_Instance;
}
