/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    programId_ACC_PC.h
 *
 * @author  Generated by ASCET
 *
 * @brief   Program ID definition
 *
 **/
#pragma once

#include "a_basdef.h"

#define UNIQUE_PROGRAM_ID (uint32)796932230U
