/**
 * @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
 *
 * @file    ShutdownHook
 *
 * @author  Generated by ASCET
 *
 * @brief   implementation of ShutdownHook
 *
 **/


/******************************************************************************
 * BEGIN: DEFINITION OF TASK 'ShutdownHook'
 * ----------------------------------------------------------------------------
 * model name:...................................'ShutdownHook'
 * memory class:.................................'CODE'
 * priority:.....................................'-'
 * period(ms):...................................'-'
 * scheduling:...................................'-'
 * ---------------------------------------------------------------------------*/
void ShutdownTask()
{
	/* no method calls defined */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF TASK 'ShutdownHook'
 ******************************************************************************/
